### ISSUE TITLE
What exactly does this do?

### ISSUE THREAD

**Issue by Johnny112233** [AiYinZiLeGong/PUBG-Radar#1]
Is it like an external Minimap which can be used on another computer?

**Comment by AiYinZiLeGong** [comment]
Currently it sniffs packets on the same computer. You can rewrite the sniffing code to support remote sniffer. Decoding part is the same.

**Comment by Johnny112233** [comment]
Does it work with the packet encryption which was announced? Not sure if the encyption is already implemented though. This is 100% undetectable if it is run on another PC, right? It just reads packets but doesn't send them, is that correct?

Since im not a dev myself I would have to find someone who can code the remote sniffer.

**Comment by AiYinZiLeGong** [comment]
No. packet encryption will render sniffer useless. 
Yes. mine radar just reads packet.

**Comment by Johnny112233** [comment]
Okay. But for now you are sure this won't work with a local vpn? If i run this radar on a second pc and connect with my gaming pc to it via vpn, dont they share the same network then so the pc with the radar has access to pubg traffic?

**Comment by Johnny112233** [comment]
Well I got it to work now but after closing the Network interface, the Radar becomes grey and no map is shown.

I set up the Radar on my laptop and I play pubg on my computer. 
The computer is connected via ethernet to the laptop. The laptop gets his internet via wifi.

I can chose between PPTP tunneling and Direct. The dropdown lets me chose my Realtek PCIe GBE Family Controller or Microsoft. None of them work. Neither in PPTP or Direct mode.

Can you tell me how to solve that? Playing the game is no problem and the internet bridge to my laptop works fine. Seems like the radar doesn't get the packets....

**Comment by AiYinZiLeGong** [comment]
Try wireshark, see if it reads any packets.

**Comment by Johnny112233** [comment]
Hi,
i tested it with wireshark. I get the packets but the radar remains just grey.

What i do:
1. java -jar pubg-radar-1.0-SNAPSHOT-jar-with-all-dependencies.jar

2. select the same interface as on wireshark (ppptp or direct, both dont work)

3. radar starts. i got about 10 seconds windows loading animation on my cursor and then the radar window gets completely grey.

do you have any idea on how to get closer to a solution? :( 
will provide u any information you need

Best regards

**Comment by Marv63** [comment]
At mine the Grey thing doesn't even show up after I selected the network🤷‍♂️

**Comment by Marv63** [comment]
I'm on Vista 32bit Java jre1. 8.0_161 and Wireshark receives packets
