### ISSUE TITLE
Player position.

### ISSUE THREAD

**Issue by Anon1984** [AiYinZiLeGong/PUBG-Radar#10]
Hi,

The program looks good but for some reason. my position is always fixed to the starting point.
Is see everybody moving except me. (green Dot)

**Comment by jobsbe7** [comment]
how?

**Comment by Psycho7** [comment]
This repo only check outgoing 44-byte packet (86-byte in total) for self position. Maybe you can modify [this part](https://github.com/AiYinZiLeGong/PUBG-Radar/blob/master/src/main/kotlin/pubg/radar/sniffer/Sniffer.kt#L224) to check incoming packet with 186 bytes, which also contains your own position in the last 12 bytes.

**Comment by AiYinZiLeGong** [comment]
Wow, I didn’t know if there is other way to get self coords. What is the incoming 186 bytes used for?

**Comment by Psycho7** [comment]
@AiYinZiLeGong I don't know neither... I just found out the last 12 bytes are also corresponding to your own position. They are RTP packets.

**Comment by AiYinZiLeGong** [comment]
@Anon1984  Somtimes the RTP packets wont't be sent. Also RTP packets won't be sent when you use the mic...

**Comment by Psycho7** [comment]
@AiYinZiLeGong I just can't figure out why BlueHole is using RTP to transfer self position and voice... Are they stupid or something? Actually, networking without encryption is stupid enough XD

**Comment by AiYinZiLeGong** [comment]
maybe try to reuse some old code.

**Comment by Anon1984** [comment]
Tried it on my game computer. here it's working. 
But on a laptop with port mirror not. Then i only see the other players and own char stuck in the corner

What could it be...

**Comment by jobsbe7** [comment]
@Anon1984 so my laptop has this error.

in the game working, but jump the fly and drop earth not working.

**Comment by lane686** [comment]
I got same issue, I'm running the code on a linux with bridge connection but my player coor is not right.

**Comment by OprekerSejati** [comment]
My player position stuck at where I landed after jump

**Comment by JayJTD** [comment]
Ubuntu 16.04.3 running on another PC on the same LAN

Same issue, player icon is just permanently stuck at the starting area.

**Comment by M0rtale** [comment]
Same problem here, despite changing the packet size checker to 56 raw bytes, the player position still remain dormant.

**Comment by AiYinZiLeGong** [comment]
commit cea997f90c04552a32d670e24639250641c8d75f should fix.
