### ISSUE TITLE
Windows 1PC use.

### ISSUE THREAD

**Issue by jeffersondenzer** [AiYinZiLeGong/PUBG-Radar#100]
Hey men, u have a VERY SIMPLE tutorial to use this hack on windows 10x64?

I HAVE ONLY THE GAME PC, don't have 2 PC'S

Specs:
System - WIN 10 x64
Pc name - SA
Java patch - C:\Program Files (x86)\Java\jre1.8.0_161\bin
radar zip name - PUBG-Radar-master.zip

Thx

**Comment by AndrewPowers15** [comment]
You will want to create a virtual machine, bridge the networks, and then install the Radar on the VM.

**Comment by jeffersondenzer** [comment]
is not needed, i do it work on my game pc

**Comment by AndrewPowers15** [comment]
I know you've closed this issue, but I'd like to add some clarification.

Not running it in a VM increases your chance of being banned.

The anticheat can see what programs you are running on your computer. Currently, it detects VMware as well, but you don't get banned for using it, just kicked.

It is up to you if you get banned running it on the same OS instance.
