### ISSUE TITLE
Nothing happens after selecting net interface - where's the problem?

### ISSUE THREAD

**Issue by snu-snu-snu** [AiYinZiLeGong/PUBG-Radar#102]
Hi. just a question and hopefully you can help me to solve this....

Compiled it with maven without issues. great work!

So, trying to run on machine with Intel graphics (openGL 3.1 support only)

1. get the option to select network interface
2. select any of them. 
3. Press OK
and nothing after that. nothing happens.

any suggestions?
winpcap is installed.

btw, none of the forks work.

thanks in advance.

**Comment by Norxy** [comment]
You need to launch it first, and join a game after.
How do you use it, in VM?
