### ISSUE TITLE
How can i use it

### ISSUE THREAD

**Issue by huochai67** [AiYinZiLeGong/PUBG-Radar#104]
i run 
`java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar "192.168.1.2" PortFilter`
but it is useless

**Comment by Tekyera** [comment]
try
`java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.1.2 PortFilter`

also you could rename it to
`pubg-radar-with-dependencies.jar`

and try again. 

Make sure that your local ip is 192.168.1.2

**Comment by jeffersondenzer** [comment]
[https://youtu.be/T6Q3onoK-dM](url)

**Comment by jeffersondenzer** [comment]
https://youtu.be/T6Q3onoK-dM

**Comment by Pochtidruid** [comment]
some mod's ban this ^ fucking degenerat.

**Comment by huochai67** [comment]
Thanks
