### ISSUE TITLE
Can I run it in browser?

### ISSUE THREAD

**Issue by justan0therone** [AiYinZiLeGong/PUBG-Radar#108]
I have only one monitor. So it’s a little bit hard to alt+tab everytime. Can I start it in local network to connect via phone?

**Comment by pubgrad** [comment]
If you have windows 10 on gaming pc, open another desktop and open the radar in that desktop either on that pc or in vm. create a shortcut for switching desktops I use ahk usually but pubg bans ahk so figure that out. I use 2nd pc for radar though.

**Comment by Dragonflyss** [comment]
@pubgrad do you know were i can find a good thread about using a second pc? I hear al got banned by using VM so i like to setup a VPN.. Hope you can help out!

Kind regards from Holland

**Comment by pubgrad** [comment]
You dont get banned for using vm but get kicked form game in 5 mins and need to start another game hence using vm not a viable option. The radars on github got deleted and detected by battleeye.

Here is a guide on how to use it on 2nd pc:
https://pastebin.com/yiemJLw8

I think this guide doesnt mention opening ports. If your vpn shows error and doesnt connect you have to add 1723 port in firewall on both pc
