### ISSUE TITLE
Item filtering help and new item icon request. Still its best radar ever.

### ISSUE THREAD

**Issue by Jeziu** [AiYinZiLeGong/PUBG-Radar#109]
Hey!
i have problem with your item filtering. Program is compiled with maven on ubuntu, and run on my gaming pc with this vbs script "Set PUBGR = CreateObject("Shell.Application") 
PUBGR.ShellExecute "javaw.exe", "-jar data.jar 0 PortFilter 0", "", "runas", 1 ". I am trying to write something on created window but nothing happens. Also can You change this geometric things to items mini photos like on other radars, its much more comfortable. Thanks in advance for help and thanks for sharing so good radar, with very low cpu usage (i used to have on with took me 30% of cpu now its only 1%).

**Comment by CatFaced** [comment]
I repackaged the png page of sprites because i didnt like the icons

I also changed the hotkeys and labeled them in the UI display so it's easier for a new user to hit the ground running.

I found changing the zoom distance for icons to a farther distance more beneficial as well.
