### ISSUE TITLE
2d-3d kotlin

### ISSUE THREAD

**Issue by forsakeN1337** [AiYinZiLeGong/PUBG-Radar#11]
hey, i know this is just indirectly something about the radar, but are you willing and able to contribute a 2d->3d translation in this language? 🍡

**Comment by Psycho7** [comment]
Z is already there. All you need is to add few lines of code to make use of it.

IMHO, 3d is useless unless you are going to directly draw something on screen.

**Comment by forsakeN1337** [comment]
Thats what i want to do :D

**Comment by Psycho7** [comment]
Well it will help a lot since you won't be distracted. But I think it's slight more demanding as you need to translate world space coordination into view space.

**Comment by forsakeN1337** [comment]
the problem might also be that i never heard of kotlin ever before lol
