### ISSUE TITLE
what is the latest radar.  i want to find it 

### ISSUE THREAD

**Issue by bf1515431927** [AiYinZiLeGong/PUBG-Radar#113]
can you give me a website? because i find many source code in github. whose is the latest?

**Comment by ehoerr** [comment]
Many people are simply changing the code a little bit or creating their own program to do the tasks for you. However, I would not say their improvements justify their pricing. At those prices, you could just buy a real cheat with item esp in the game and not have to keep looking at a second PC/monitor. 

**NOTE:** I have noticed many people saying they are receiving bans, myself included, from using this radar. I would be careful as you continue forward in choosing which cheat to use.

https://www.elitepvpers.com/forum/playerunknowns-battlegrounds-trading/4427967-100-undetectable-packetmap-v2-0-network-traffic-radar.html

https://www.elitepvpers.com/forum/playerunknowns-battlegrounds-trading/4434971-battleradar-pubg-radar-packet-based-100-undetectable-10-week.html

https://www.elitepvpers.com/forum/playerunknowns-battlegrounds/4389314-100-undetectable-pubg-radar-packet-based.html

**Comment by Cron5** [comment]
By "changing the code" you mean variables? Or smth else?

**Comment by CatFaced** [comment]
Ignore everyone trying to sell you something.

https://github.com/FutureXpo/PUBG-RADAR-8K

Future collaborated with Jerry and SamNZ on this. His latest repo is decent and easy enough to modify for your purposes.

**Comment by noise87** [comment]
no seem work this radar :/

**Comment by Krypt0HaZe** [comment]
What error do you have? @noise87

**Comment by CatFaced** [comment]
@noise87 Might be weird but drop your discord and i'm happy to reach out and assist.

**Comment by noise87** [comment]
![immagine](https://user-images.githubusercontent.com/36767858/37087613-17386756-21fb-11e8-81eb-09300fdbfc7c.png)
 this is the error... i try with precompiled file and with code compiled by myself, same error

my discord noise87#2619

**Comment by noise87** [comment]
i try use last jerry radar with arpspoof from middle pc, all start but radar stay grey

**Comment by CatFaced** [comment]
@noise87 I'll send you a package I built on discord.

**Comment by SamuelNZ** [comment]
**Permanent** bypass for all kernel based anti-cheats incoming, They seem to have forgotten something important about kernel land.

**Comment by Dragonflyss** [comment]
@CatFaced may I add you to? I would like the file you created aswell.. if it works ;)

**Comment by noise87** [comment]
@CatFaced thx for help ^^
