### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Norxy** [AiYinZiLeGong/PUBG-Radar#12]
Hello, thanks for your sharing but i can't make it works :(

I tried all 3 jar ( dependencies, sources, default)

When i click on it, nothing happen, I will tell you what I did maybe you will see the problem somewhere

-installed winpcap/wireshark
- Installed maven ( did the path, m3_home etc changes)
- Installed java jdk ( did java_home change)
- i launched cmd w/ admin rights : cd "the path of the unzip folder"
- mvn package (tried mvn install too)

the software do the work, some notifications like "playerhead" (its an exemple) is not used anywhere. 

reho(dot)st/self/b2bccaf8afb50381f560edd9fd3d9c56e3fd2372(dot)jpg

Plus the build say :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

Guess that's not normal, isn't it?

But after that i got a message saying build successful and I have 3 executables

And like I told you, when I click on it nothings happen.

I did a fresh install of my W10

**Comment by Norxy** [comment]
Do I have to launch it only when i'm in game on PUBG on my another computer?

**Comment by Anon1984** [comment]
How do you start it?
java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar should work

**Comment by Norxy** [comment]
Here is what happen when i do this command : 

reho(dot)st/self/dcc4f7449d76d5f23770a9393f2b9b47c8738cc3(dot)jpg

**Comment by Norxy** [comment]
Is it normal all those warnings? I have 93 warnings

**Comment by Norxy** [comment]
Ok, it works fine thank you Anon1984, and thanks to the creator for his share!

For those with the same problem I had, launch the radar first, then join a game
