### ISSUE TITLE
Where is linux branch?

### ISSUE THREAD

**Issue by PiniginS** [AiYinZiLeGong/PUBG-Radar#124]
I have RenderBadPicture error on linux. Where is linux branch? I want to use my laptop for radar. It's safe?
![github - aiyinzilegong_pubg-radar - google chrome 2018-03-09 15 17 06](https://user-images.githubusercontent.com/5118635/37199912-4373e116-23ad-11e8-8861-e2c890449c97.png)

**Comment by hkuuki** [comment]
run at macos and everything good

**Comment by Mykybo** [comment]
https://github.com/Mykybo/PUBG-Radar forked linux branch & updated

**Comment by PiniginS** [comment]
@Mykybo Ok) Now i run this, but i have gray screen without any interface. Have you any idea how to fix run it?
I change interface name in run.sh and arp.sh and i change my router ip in arp.sh (i have 192.168.100.1)

**Comment by PiniginS** [comment]
@Mykybo Thx a lot man)
