### ISSUE TITLE
Latest update broke the radar

### ISSUE THREAD

**Issue by Jerry1211** [AiYinZiLeGong/PUBG-Radar#127]

**Comment by pubgrad** [comment]
Latest version showing black screen when radar opens. Nothing happens when I join the game. Any idea how to fix?

**Comment by pubgrad** [comment]
Btw jerry can you invite me on gitlab to your repo?

**Comment by pubgrad** [comment]
Check pm on uc .me website

**Comment by bracikk** [comment]
Jerry1211, could you write how to set this ports? Thank you

**Comment by GoodMEHT** [comment]
can you invite me into your repo too?

**Comment by theone8x** [comment]
@Jerry1211 can u add me to your repo too?
Thank You

**Comment by baldinio** [comment]
@Jerry1211 I would like an invite too please, same username

**Comment by niklaswi7** [comment]
@Jerry1211 Can you throw an invite my way as well.

**Comment by Anon1984** [comment]
same here please throw me a invite

**Comment by up6gj94ek** [comment]
@Jerry1211  same here please throw me a invite

**Comment by mindsailor** [comment]
Would love an invite as well if possible.  Thank you

**Comment by caoliu1118** [comment]
@Jerry1211 Would love  an invite as well. I love your fork.

**Comment by Al1-mert** [comment]
me too :P

**Comment by mcalis** [comment]
@Jerry1211 If I could get an invite pls. Many thanks

**Comment by arithxp** [comment]
@Jerry1211 please invite me to your repo 👍 
I really like your changed

**Comment by sukareki** [comment]
@Jerry1211 Can you invite me to your repo too? Thanks

**Comment by caoliu1118** [comment]
@Jerry1211@AiYinZiLeGong The Radar is broken in test Server.maybe it will not work in the next version.

**Comment by kajaaakaka** [comment]
@Jerry1211 can you invite me to your repo too? loved your fork

**Comment by caoliu1118** [comment]
The lastest version today may break the radar.
because the Radar is broken in the test Server on March 9.
the server will update to the test server version today.
