### ISSUE TITLE
Help me. I have Player position fixed problem

### ISSUE THREAD

**Issue by arithxp** [AiYinZiLeGong/PUBG-Radar#140]
I have tested some methods(arpspoof, vpn, offline mod.
But everything did not work. It is fixed at the upper left corner.

Does anyone else have this problem?
May I know how to solve it?

Thank you

**Comment by arithxp** [comment]
solved.

**Comment by Anon1984** [comment]
And how did you fix this?

**Comment by 748aef305** [comment]
Oh god, please tell me @arithxp how did you manage to fix this???

**Comment by arithxp** [comment]
https://pastebin.com/HTs9ktGF
I saw jerry1211's edited source.
Find ip.header.srcAddr and delete

Maybe ip check func. But we using 2nd pc. So localAddr (radar pc) and ip.header.srcAddr (gaming pc) value is  diffrent.

Thank you @Jerry1211
:)

**Comment by arithxp** [comment]
Updated source. @Redder1337 or @Xvender
It works
