### ISSUE TITLE
The radar not working after the update March 12th

### ISSUE THREAD

**Issue by lane686** [AiYinZiLeGong/PUBG-Radar#149]
The radar not working after the update March 12th any hint or fix?

**Comment by caoliu1118** [comment]
The lastest version today may break the radar.
because the Radar is broken in the test Server on March 9.
the server will update to the test server version today.

**Comment by caoliu1118** [comment]
mb packets structure changed.
wish @AiYinZiLeGong can fix it.

**Comment by feedju** [comment]
Can confirm, screen is no longer loading.

Anyone have any resources on the new packet structure? I'd be happy to fork and update

**Comment by piktos** [comment]
@AiYinZiLeGong you are the best we know you can to fix 🥇

**Comment by arnanmaipradit** [comment]
That 1.9 GB updated can't stop @AiYinZiLeGong for sure !!

**Comment by SayRivera** [comment]
confirm

**Comment by aznxfrost** [comment]
Perhaps @AiYinZiLeGong can release a very simple guide on how we can capture new structure with wireshark and update the packetparser.

**Comment by OprekerSejati** [comment]
@aznxfrost yess ....... that would be nice

**Comment by xXSkrill1337** [comment]
Yes it would be a good idea ;)
@aznxfrost

**Comment by EiTeR94** [comment]
lol, i don't think to capture structure is as simple as you think.
Let the coder do it, if they want, and can.
They have real life. Be patiente until an update come

**Comment by xXSkrill1337** [comment]
Ye yeee

**Comment by piktos** [comment]
One person confirm. Private Map-Hacks are working.

**Comment by xXSkrill1337** [comment]
Yess i see this ...
@piktos 
Just wait for the next update

**Comment by lllteolll** [comment]
Can't wait 👍

**Comment by EiTeR94** [comment]
@xXSkrill1337
Have you a private github radar hack ?

**Comment by xXSkrill1337** [comment]
You do you have it ?? 
@EiTeR94

**Comment by Dragonflyss** [comment]
cant wait! if there is anything i can help with, let me know!

**Comment by DeveloperUnknown** [comment]
For a start, there is an extra bit needing to be read after bReliable in PacketParser.kt

Adding readBit() after bReliable = readBit() will get some of the stuff working again.

**Comment by 748aef305** [comment]
@DeveloperUnknown pardon my ignorance but when I added readBit () after bReliable = readbit() in the PacketParser.kt file, I only get Build/compilation failures when trying to run it. 

I get "[ERROR] failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.2.30 compile (compile) on project pubg-radar: Compilation failure: compilation failure: 

[ERROR] C:\PUBG\PUBG-Radar-master\PUBG-radar-master\src\main\kotlin\pubg\radar\deserializer\PacketParkser.kt: [53, 39] Expecting an expression

[ERROR] C:\PUBG\PUBG-Radar-master\PUBG-radar-master\src\main\kotlin\pubg\radar\deserializer\PacketParkser.kt: [53, 31] Unresolved reference: readBit"

Any chance you can tell me what I'm likely doing wrong here?

**Comment by fillorkill** [comment]
@748aef305 you need to learn some coding.

**Comment by 748aef305** [comment]
@fillorkill You're not wrong! I'm by all admissions an idiot and a noob to all of this!

**Comment by Norxy** [comment]
Find Jerry1211 Repo, the radar is up to date !

**Comment by whitewingz2017** [comment]
https://github.com/Jerry1211/Radar

**Comment by StopperNZ** [comment]
Thanks DeveloperUnkown  worked a treat....

**Comment by StopperNZ** [comment]
@748aef305  you need to create a bullshit variable (value i mean lol) to pack things out...   val  doesNothing =readBit()

Thanks @DeveloperUnknown  by the way.

**Comment by caoliu1118** [comment]
Thanks @DeveloperUnknown

**Comment by nyetwurk** [comment]
Why was this closed?
