### ISSUE TITLE
nodejs version.

### ISSUE THREAD

**Issue by txchen** [AiYinZiLeGong/PUBG-Radar#153]
I have just published my nodejs repo. Check it out: https://github.com/txchen/scichicken

However please don't ask questions, since I am not playing the game anymore. I believe the code is not hard to understand, so please enjoy DIY hacking.

**Comment by whtiehack** [comment]
ty for share

**Comment by howyay** [comment]
you are a legend

**Comment by nengbowan** [comment]
/Users/fushiyong/gitRepos/scichicken/backend/index.js:11
app.use(async (ctx, next) => {
              ^
SyntaxError: Unexpected token (


please tell me what version of node .. or how to resolve 

@txchen

**Comment by txchen** [comment]
@nengbowan try using latest nodejs, like 9.8

**Comment by nengbowan** [comment]
it can work ,node version up 7.0 . 
but only display one map , how it can start . for example . 
url:port/start  , it can not be work

**Comment by nengbowan** [comment]
@txchen

**Comment by liantian-cn** [comment]
Good Job!

**Comment by xandy5004** [comment]
How to relocate the enemy's base address ？
