### ISSUE TITLE
any working fork atm?

### ISSUE THREAD

**Issue by SoHyped** [AiYinZiLeGong/PUBG-Radar#156]

**Comment by wuwujia** [comment]
like what paid radar?

**Comment by liantian-cn** [comment]
like paks file,  packets are encrypted by aes with static key. 

if you got key , you can decryption packets 

but if you open source . bluehole will use ssl encryption asap , which is supported in UE4.18

https://docs.unrealengine.com/en-us/Support/Builds/ReleaseNotes/4_18#networking

**Comment by SoHyped** [comment]
the keeping it close source wont let blueballs patch it is such a stupid reason not to release it @liantian-cn ,the decryptor is already out on UnKnoWnCheaTs and on github

https://github.com/nmodnation/pubg_decryptor

and i hope pubg would go SSH or whatever because that would at least make it even grounds with ppl who are willing to buy the monthly $30 and us.
