### ISSUE TITLE
Radar works but map Image doesnt display

### ISSUE THREAD

**Issue by boludo123215** [AiYinZiLeGong/PUBG-Radar#16]
The radar works fine, but there is no map image, the background is all gray
Do you have any idea why?

**Comment by AiYinZiLeGong** [comment]
Supported maximum Texture size should be 8192. If not, replace the image by smaller one.

**Comment by AiYinZiLeGong** [comment]
You can find smaller one in branch Linux, which is 4096.

**Comment by boludo123215** [comment]
thanks, ill try

**Comment by boludo123215** [comment]
nevermind, saw your commit and fixed it
