### ISSUE TITLE
Outdated map images, slight item/player position issues, item's not disappearing when picked up

### ISSUE THREAD

**Issue by michaelpittino** [AiYinZiLeGong/PUBG-Radar#2]
Hey, great tool so far, just some issues I've encountered:

- The map images are outdated, the last update modified/added/repositioned some buildings
- Player/Item icons are slightly off of the real position (this could be related to issue 1)
- I haven't looked into the bitstream, but it'd be great if icons would disappear if picked up

Just some thoughts,
Best Regards

**Comment by AiYinZiLeGong** [comment]
Welcome contribution.
I haven't figured out item position's weird offset.

**Comment by michaelpittino** [comment]
I'd love to contribute, but never touched Kotlin :b
Did you notice that the Radar has a performance impact sometimes? I've tried to limit it's FPS to ~20 but that doesn't help. What helps is making the Radar window smaller (~500x300).
Do have an idea what causes this?

**Comment by AiYinZiLeGong** [comment]
Map image is 8192x8192.

**Comment by michaelpittino** [comment]
Yeah, but this shouldn't cause a performance drop of ~40 FPS in the game, should it?
If thats the case, would it possible to split the map images into smaller parts and render only the parts visible to the viewport?

**Comment by michaelpittino** [comment]
I do run PUBG in fullscreen exclusive, with the map on the second screen.

**Comment by AiYinZiLeGong** [comment]
well. I used GTX 1080 and experienced no severe drop of fps.
May be it is related to the maximum texture size? 8192 may not be most accepted texture size.

**Comment by michaelpittino** [comment]
I only have a GTX 960, maybe thats the issue :b.
Besides, do you know if the RTP packet also transmits the player rotation? Currently it looks like that the rotation is calculated using a delta of new and old position, witch can cause wrong results when walking backwards/sidewards while still looking front.

**Comment by AiYinZiLeGong** [comment]
No. Player rotation isn’t in RTP packet. Velocity direction is the only thing I can do.

**Comment by michaelpittino** [comment]
I see, and about the issue that items remain on the map even when picked up? Is this not transmitted by the server?

**Comment by AiYinZiLeGong** [comment]
Item clearing can be implemented. Picked up items will be `DroppedItem` and attached to player.

**Comment by alangregory** [comment]
@AiYinZiLeGong is there any reference to a uniqueId for each item on packets?

**Comment by AiYinZiLeGong** [comment]
Each object will have unique network GUID.

**Comment by alangregory** [comment]
Looks like that GUID is for the drop group, this cause the wrong coordinates.
Every drop group that contains more then one item, does not mean they spawn at the same coordinate.
There should be an individual item coordinate/ofset.

**Comment by mjmfighter** [comment]
Is there a specific place where you are getting all the RepLayout data from?  I would like to help out with some of these things, but this is the last thing that I can't find anywhere.  Is it something in the UE4 source code or is it something that is just discovered by trial and error?

**Comment by PubgKnown** [comment]
Made an attempt at doing tiled images. It most likely could be improved. I have no idea how the performance is with it. However the repo also uses images instead of shaped icons for items. So the performance is already worse. Might be possible to cherry pick the commit below to get the tiled images changes.

https://github.com/PubgKnown/PUBG-Radar/commit/09a6f5502aa77994d8322966027f7146d56078a7

**Comment by solixa** [comment]
is it the Z axis thats throwing the loot positions off, is there a way to read the z and compensate?

**Comment by michaelpittino** [comment]
No, Z is height.
The offset is caused by using the group position and not the individual item position

**Comment by TheBlackGolem** [comment]
Did anybody figure out how to get the individual items position/coords? Can't seem to get it to work.

**Comment by AiYinZiLeGong** [comment]
commit 8c058f747dfef88928002aa13ef02500362be1a6 should fix
