### ISSUE TITLE
Use the radar on another computer

### ISSUE THREAD

**Issue by Norxy** [AiYinZiLeGong/PUBG-Radar#20]
Hello, 

The radar works well, but to be safe from BE i'm trying to make it work on my other PC, but I don't really know how to do that. I can see the packets of my gaming PC, not on my 2nd computer

Can someone help me a little bit? Thanks 👍

**Comment by lane686** [comment]
I tried both WIN10 or LINUX but not success at all, LINUX has no player coor for your self and win10 have the same problem plus the map does not show.

**Comment by Norxy** [comment]
You need to launch the radar in the main menu, and join a game after to make it works. That worked for me

**Comment by lane686** [comment]
I can make it run on the same computer as game is running but not a VM or remotely.

**Comment by Norxy** [comment]
Ah, same for me, VM doesn't work even with PPTP tunneling?

**Comment by lane686** [comment]
Not able to setup one ...

**Comment by Norxy** [comment]
Can't help you, I don't use VM sorry

**Comment by Norxy** [comment]
Thank you for your answer, when I do everything you said in the updated readme, the radar stay grey and don't change, I tried both PPTPFilter and Portfilter option

**Comment by Norxy** [comment]
No one?
