### ISSUE TITLE
Own PlayerLocation & No-Map inside a VM (HOW TO FIX!)

### ISSUE THREAD

**Issue by TheUserUnknown** [AiYinZiLeGong/PUBG-Radar#22]
Hello,

For everyone who is having problems getting this to work, Here is how to resolve those 2 main problems:

- First Problem: No-Map (Black map) (Windows)
Download the 2 map images from the [Linux Branch](https://github.com/AiYinZiLeGong/PUBG-Radar/tree/linux/src/main/resources) and put them in the same location for the main branch, Then edit the code like the following [commit ](https://github.com/AiYinZiLeGong/PUBG-Radar/commit/32182dc838041124a0cffa60bd45cd3548615551)

This should resolve the "black map"

- Second Problem: Own PlayerLocation not correct
Check my [Pull Request](https://github.com/AiYinZiLeGong/PUBG-Radar/pull/21)

Also pressing your VOICE button (for me this is T) at the beginning of the round is required since pubg only sends your own location when you at least used voice-chat once

**Comment by lane686** [comment]
still got no map in Linux by using those two maps

**Comment by Norxy** [comment]
Same, but in W7 VM

**Comment by TheUserUnknown** [comment]
@lane686 @Norxy Also make sure to do [this ](https://github.com/AiYinZiLeGong/PUBG-Radar/commit/32182dc838041124a0cffa60bd45cd3548615551)

**Comment by lane686** [comment]
Thanks for the fast reply I will give it a shot.

**Comment by TheUserUnknown** [comment]
@lane686 No problem, I'm currently remaking this in C#/HTML5, so you can run it on your mobile or anything you want.

**Comment by Norxy** [comment]
Thanks for your answer, i'm really interested in your project if you will share it, because my knowledge is low and I have no idea how to use it on another PC/mobile 

I will try your answer thanks

**Comment by OprekerSejati** [comment]
Hi @TheUserUnknown ,

I tried on w7 vmware on VmWare Workstation 14 Pro, but it keep saying my opengl is only 2.xx and need opengl at least 3.1.

Have any idea how to solve this opengl problem?

**Comment by TheUserUnknown** [comment]
@OprekerSejati Make sure you have the following enable in your VM configuration: Accelerate 3D graphics, Also make sure to install VMware tools, then reboot your machine and try again.

**Comment by OprekerSejati** [comment]
@TheUserUnknown  Thanks, I will try your idea

**Comment by arithxp** [comment]
thanks!
it's works for me.

**Comment by lane686** [comment]
Tested all this, working very well ;) 
Thanks!

**Comment by diegodp** [comment]
I do not understand this  " Download the 2 map images from the Linux Branch and put them in the same location for the main branch, Then edit the code like the following commit "

I download what files?  what folder do i put them ?

**Comment by AiYinZiLeGong** [comment]
#14
