### ISSUE TITLE
Can I display item names?

### ISSUE THREAD

**Issue by arithxp** [AiYinZiLeGong/PUBG-Radar#24]
If the item name is shown, it would be easy to see.

thank you shared !
👍

**Comment by boludo123215** [comment]
I am trying to modify the code to draw the names..

**Comment by arithxp** [comment]
@boludo123215 I hope it succeeds. 👍

**Comment by pdzzzn** [comment]
Have a look at the drawItem() function in the GLMap.kt file. 
I haven't tested it, but you should be able to draw the name by adding something like 
`itemFont.draw(spriteBatch, "$items", x + 2, windowHeight - y - 2)`
Just some pseudo code, no idea if it actually works. Can't test right now

**Comment by arithxp** [comment]
@pdzzzn Im already try this. it's not works for me

`Exception in thread "main" java.lang.IllegalStateException: SpriteBatch.begin must be called before draw.`

**Comment by boludo123215** [comment]
you have to surround it with 
paint(camera.combined) {

to get rid of the error, but still doesnt work

**Comment by Jerry1211** [comment]
find `val generator = FreeTypeFontGenerator` and add
```
    param.color = ORANGE
    param.size = 42
    itemFont = generator.generateFont(param)
```
put `itemFont.draw(spriteBatch,"$items" , sx, syFix)` under ` draw(iconImages[it], sx, syFix)`

and put ` littleFont.dispose()`  under `littleFont.dispose()`
 
Tested and works for me

**Comment by FrZ-BR** [comment]
@Jerry1211 

can't find `draw(iconImages[it], sx, syFix)` it in GLMap.kt

**Comment by Jerry1211** [comment]
@FrZ-BR https://github.com/Jerry1211/PUBG-Radar/commit/9459c8780cdc20e2c293119496d86fd49e535e16

**Comment by FrZ-BR** [comment]
Great work @Jerry1211 im learning alot with those changes... i also saw that you add some icons variables... i have made my custom icons, if i add them to the source they will be showed? thanks.

**Comment by Jerry1211** [comment]
Thanks but its @PubgKnown work ive just been tinkering with his code. aslong as you put the Icons in /Resources/Icons should be fine.

**Comment by Pochtidruid** [comment]
@Jerry1211 can u update ur link pls

**Comment by pornodog** [comment]
I can't see items on map?

**Comment by Tekyera** [comment]
@Jerry1211 could you help, please?
![default](https://user-images.githubusercontent.com/32346610/36602811-07986f74-18ca-11e8-82db-8b78f1fce2ab.PNG)

**Comment by pornodog** [comment]
@Jerry1211 same issue i get when I use your fork

**Comment by Jerry1211** [comment]
@pornodog zoom in

**Comment by Jerry1211** [comment]
@Tekyera u forgot to choose portfilter

**Comment by pornodog** [comment]
@Jerry1211  even when I zoom in no items for this fork. But for your port i can't run it at all. I get this error

C:\Users\*******\Documents\Radar\Jerry1211\target>java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 120.28.161.37 PortFilter
0
0
0
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:48)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:207)
        ... 1 more

**Comment by Tekyera** [comment]
@Jerry1211 what is portfilter and how to choose it? Because in others forks I don't need it to start the radar

**Comment by Jerry1211** [comment]
@pornodog you're using the wrong IP Address..... goto cmd, type ipconfig look at the Ethernet Adapter and the ip should be 192.168.x.x or 10.x.x.x

**Comment by pornodog** [comment]
@Jerry1211 f*** thanks man!! i've been going crazy for a while not trying to make it work. runs now. time to test it in game
