### ISSUE TITLE
Latest game update made some protocol changes?

### ISSUE THREAD

**Issue by michaelpittino** [AiYinZiLeGong/PUBG-Radar#25]
Seems like the latest game update made some changes to the protocol.
While the radar still works (in some way), it only shows my position and my teammates positions.
Enemies seem to be stuck on certain positions/only update very slowly. Items don't show at all.

**Comment by AiYinZiLeGong** [comment]
Haven’t experienced your problem.

**Comment by pdzzzn** [comment]
Still working fine on my side aswell. Only thing I have been experiencing is that the camera is focused on my player, which after landing and playing for a minute becomes dormant and doesnt move anymore.

**Comment by Mykybo** [comment]
Yep, same happens to me sometimes. Usually happens if I play squad or duo, never in solo.

**Comment by bernieplayshd** [comment]
When you come down with the parachute, the local player(and camera) freezes on the radar from a certain height to the ground. For me this happens every round and stays till the game ends.

**Comment by mrspartak** [comment]
>freezes on the radar from a certain height to the ground
Same for me.

**Comment by AiYinZiLeGong** [comment]
#14 #2
