### ISSUE TITLE
Player position stuck

### ISSUE THREAD

**Issue by mrspartak** [AiYinZiLeGong/PUBG-Radar#27]
Every match at the end of airplane path green point get stuck. I'm dissapearing from map and if I get car I will appera as red enemy dot
https://i.gyazo.com/2008209cc4366dbdc6a7521a024dd6ac.png (my real position is at blue arrow)

So I can't scroll the map, it always fixed at wrong position and then at the end of the game (~after 20 min) position changes to far far away from the map

**Comment by Norxy** [comment]
Press "Push to talk" button at the beginning of the game

**Comment by mrspartak** [comment]
I saw other issues. I tried it, also I tried to add this commit https://github.com/AiYinZiLeGong/PUBG-Radar/pull/21/commits/e7e110101f88b9a2f0365e49def09b856cf5a482
And it didn't help

**Comment by AiYinZiLeGong** [comment]
#14
