### ISSUE TITLE
GLFW_PLATFORM_ERROR & Grey Screen

### ISSUE THREAD

**Issue by JurishCrypter** [AiYinZiLeGong/PUBG-Radar#28]
Hello, I've build with maven, it worked without a problem, tried building the master branch and the linux, I had to use the linux branch since it gave me RenderBadPicture issue. I would do everything correctly and get grey screen, even so I tried opening a pubg match, when the match started I got the following problem:
```
[LWJGL] GLFW_PLATFORM_ERROR error
	Description : X11: RandR monitor support seems broken
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:2296)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:142)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:110)
		pubg.radar.ui.GLMap.show(GLMap.kt:97)
		pubg.radar.GameKt.main(Game.kt:49)
```
After reading the Issues I found this helpful post https://github.com/AiYinZiLeGong/PUBG-Radar/issues/22, done what was in it and the same thing happened, I took both the bpm for the maps from linux branch and put on master, also changed the code for that commit, got RenderBadPicture again.

I've tried to run it in windows, also tried using windows linux bash subsystem and couldn't make it work. In windows the issues would be I couldn't get a alternative to dsniff to work (I'm using winpcap on both my windows pc [the game and the one trying to be the middlepc], just not using winpcap on linux)

In my linux system I'm running the arpspoof correctly and runnin the jar, you can see at the attached screenshot.

I'm out of ideas, can't get it to work, can someone enlighten me?
![screenshot from 2018-02-11 16-56-09](https://user-images.githubusercontent.com/34819895/36077027-7cd9d020-0f4c-11e8-82ea-b0f313418959.png)

**Comment by kajaaakaka** [comment]
Hello,
I can't really help you with your error message, but an (I think working) alternative for dsniff on windows is https://github.com/alandau/arpspoof. I tried it and tested it successfull with wireshark.

regarding the radar, I tried ubuntu vm, windows 10 vm, pure windows 7 and pure windows 10 and I always got only the grey map. None of the posted solutions fixed my problem.

**Comment by foobarna** [comment]
To successfully run it on Ubuntu VM on the windows host, you need to checkout the `linux` branch and do what it says in `README`.
You also have to enable `promiscuous mode` for the VM. Open VirtualBox > settings on the Ubuntu VM > Network > Adapter (needs to be Bridge) > collapse Adavence > `promiscuous mode` set to `Allow All`

Hope it help!

PS. The adapter network needs to be set in `Bridge` mode and share the same network (physically) with the Windows host. That means, if you have cable AND wifi activated, turn off the wifi.

**Comment by JurishCrypter** [comment]
In the first paragraph of my post I told I tried out the linux branch, it didn't work, I wasn't using Virtual Machines, I was connected with a ubuntu in my network, tried with virtual machine as well, doing bridge mode, but no success.
I actually managed to run it perfectly, I changed some stuff in the code to locate my character, but I was only able to do so running in windows, thanks to @kajaaakaka .
I realised that the connection spoofing is not great, it makes the primary pc lag sometimes, since the spoofer is redirrecting his packets, gonna try to find something better to it

**Comment by Norxy** [comment]
@JurishCrypter 
Can you explain how you managed to make it work please? 

I have my gaming pc, and a laptop w/ kali linux last version installed, I compiled but I can't get it to work.
When I do a arpspoof and launch the radar, It stay grey

**Comment by JurishCrypter** [comment]
The simplest way I can instruct:
Download arpspoof from the github link kajaaaka gave, download maven for windows, extract them to individual folders, add those folders with their binary executable to the system variable path, execute arpspoof as instructed in readme, make sure your gaming computer has winpcap (so windows winsock packets can be read as udp, tcp, arp) and simply compile and execute the jar.

**Comment by Norxy** [comment]
I already tried that, but I will try again because I forgot to add arpspoof in system variable, thanks for your answer

**Comment by JurishCrypter** [comment]
You can also try just executing arpspoof from its folder, I just add to
system path cause it's easier.

Em 14 de fev de 2018 15:57, "Norxy" <notifications@github.com> escreveu:

**Comment by Norxy** [comment]
I don't understand why it doesn't work for me, I installed maven, java, wireshark, compiled it and it launch fine. downloaded > arpspoof.exe <, I put it in a folder on my desktop, radar .jar in another folder.  I open a powerhsell/cmd window : arpspoof.exe ip_gamingpc, it works fine ( how to verify ?) another cmd : java -jar radar.jar middleman_ip portfilter gamingpc_ip 

Am I doing it wrong?

**Comment by kajaaakaka** [comment]
On windows: start both cmds as administrator (right click on cmd, launch as administrator)

Verify arpspoof with tools like Wireshark. You should see a lot of packages arriving with target ip from your gaming pc.

**Comment by br14nm4** [comment]
You aren't even using arpspoof correctly -_- 
Check your syntax.
