### ISSUE TITLE
/*Gray window*/ (FIXED) localplayer position stuck

### ISSUE THREAD

**Issue by kapiwulon** [AiYinZiLeGong/PUBG-Radar#29]
Hello. Today I discovered this project, and wanted to try it out. I set up VM, and I thought everything is gonna work, but all I get is gray window. 
https://i.imgur.com/MMkJhCe.png
I'm obviously in game while trying, and I have bridged network in vmware settings.

Any help would be appreciated, if you need any more details, please let me know.

**Comment by kajaaakaka** [comment]
+1

**Comment by arithxp** [comment]
try linux branch. i used vmware, mint linux, radar linux branch.
it works without gray window

**Comment by kapiwulon** [comment]
I did try Linux branch, and I was still running into the same issue

**Comment by kapiwulon** [comment]
Ok, I got it to work, but now my localplayer position is stuck on spawn point.

**Comment by kajaaakaka** [comment]
How did you fixed it?

**Comment by kapiwulon** [comment]
I didn't, it just started to work. Make sure to first launch cheat and then start the game. Localplayer position fixed by itself too.

**Comment by kajaaakaka** [comment]
Did you just used the master branch or edited the stuff mentioned in other trheads?

**Comment by kapiwulon** [comment]
I used plain linux branch with no changes made by me.
