### ISSUE TITLE
can not using with vpn?

### ISSUE THREAD

**Issue by arithxp** [AiYinZiLeGong/PUBG-Radar#3]
I ran the radar on VMware (pptp vpn used).
It probably seemed to work.

But the map image could not be loaded. (works on game PC. not works only vmware. idk why)
And unable to update my current location.

https://imgur.com/RRfszU1

How can I fix it?

Thanks for sharing. :)

+

sorry.
It works without VPN.
👍

how to works with VPN?

**Comment by arithxp** [comment]
sorry.
It works perfectly without VPN.
👍 

how to works with VPN?

**Comment by OprekerSejati** [comment]
I'm new in kotlin, can you tell me how to compile/build this project?

**Comment by arithxp** [comment]
I know that kotlin is now.
I'm used the "IntelliJ IDEA Community Edition 2017.3.4 x64", make maven project, over write files to project folder. and build Game.kt

**Comment by AiYinZiLeGong** [comment]
actually [maven](https://maven.apache.org/) is all you need.

**Comment by whtiehack** [comment]
@AiYinZiLeGong ,  how to works with VPN? thanks for sharing:)

**Comment by mrspartak** [comment]
Does not work with vpn too

**Comment by arithxp** [comment]
@mrspartak try linux version. it's works perfect
