### ISSUE TITLE
About the "detection"

### ISSUE THREAD

**Issue by Johnny112233** [AiYinZiLeGong/PUBG-Radar#30]
I know that a passive sniffing tool on another computer shouldn't be detectable at all.

After some research i found 2 things though, that made me question the statement above:

1. https://security.stackexchange.com/questions/25011/how-can-i-detect-if-someone-is-sniffing-network-packets-on-the-lan

over here you can read about some possible detection tools. One of them can check if another client in the network is running in promiscuous mode, which the sniffer is sinca few commits ago, right?

2. In another thread about the commercial version of this radar someone talked about that it is detectable when steam "reserves nodes" of which i have no clue what he means by that. As an example he gives DankHax which has been detected in the past although it was external.

Is the deof this radarv or any other dev able to give a statement about the ways mentioned above? Do you think it is possible to detect this radar or are there any reasons that make tbe points from above irrelevant?

Thanks in advance

**Comment by PubgKnown** [comment]
1. the sniffing host is on the same Layer2 network
1. the sniffing host does not have a firewall that blocks incoming icmp packets
1. the sniffing host does the sniffing with an interface that has TCP/IP enabled, and thus is able to answer the ICMP packet.

Seems like you can easily just setup the VM or Spare computer to block icmp packets to stop detection.

**Comment by Johnny112233** [comment]
I run the radar on another computer. I bridge  the wifi to my gaming computer via ethernet. Is that on the same network layer 2. Or is my laptop layer 2 and gaming machine layer 3?

What about the "reserve node" detecting?

**Comment by kajaaakaka** [comment]
A client running its network interface in promiscuous mode shouldnt be enough to get banned, does it?

**Comment by PubgKnown** [comment]
@Johnny112233 I don't know enough about networking to answer those questions.

@kajaaakaka I would hope not but I wouldn't put it past anyone. I mean pokemon go went as far as blocking anyone with a rooted phone from playing their game using Google's Safety Net API

**Comment by br14nm4** [comment]
You aren't even using arpspoof correctly. 
Check your syntax
