### ISSUE TITLE
Scrollable map

### ISSUE THREAD

**Issue by mrspartak** [AiYinZiLeGong/PUBG-Radar#31]
Can you make map scrollable and not player fixed please? As I still have player position stuck at start, I see this is the most easy solution

**Comment by PubgKnown** [comment]
I've been making some tweaks and improvements on my fork. I haven't made any pull requests yet but I added this feature. Also not I haven't tested it in a real game yet. Feel free to build from my repo or cherry pick the commit into your existing project.

https://github.com/PubgKnown/PUBG-Radar/commit/b610d1917f442ee13c150736ac45dc5147c87938

**Comment by mrspartak** [comment]
I tried your fork yesterday. Good job with icons (but I think it is better to do them a little bit smaller). Also I still have issues with my position. Maybe there is a way to debug it?
At start location (where everyone loading) everything is ok, my point is green and move as I move. When airplane is flying I see no green icon and when I drop I'm gray and green icon moves with lags pixel behind me. When I come close to ground (or rarely when land on ground) green icon just stuck and my gray icon just dissapear. I appear on map only when in car and my icon is red.

**Comment by mrspartak** [comment]
@PubgKnown checked your latest build, everything works fine and also I see my position, thank you very much!

**Comment by boludo102938** [comment]
@PubgKnown how do you test it offline? I tried using tcpdump to save the packets in a pcal file and used the offline method in the sniffer class but it doesn't work.

Any tips?

**Comment by spAnser** [comment]
There is a line in glmap that returns if there is no map I just commented it and set the map to what I want to test. This doesn't let me test items but I was able to test the map rendering

**Comment by boludo102938** [comment]
I want to test the deserializer

**Comment by PubgKnown** [comment]
I'm sure there is a way to do it but I am not sure.

**Comment by TheUserUnknown** [comment]
@PubgKnown I've tried your fork but it is not working, getting the following error when trying to launch with the command java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar GamePCIP PortFilter

`
0
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:47)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:206)
        ... 1 more
`

**Comment by kajaaakaka** [comment]
Launch it with:

sudo java - jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar
<middlePcIp> PortFilter <GamePcIp>

TheUserUnknown <notifications@github.com> schrieb am Do., 15. Feb. 2018,
17:18:

**Comment by TheUserUnknown** [comment]
@PubgKnown @kajaaakaka Thanks, Tested and working BUT the performance is really poor (5FPS while the original is running smooth), Also icons seems to be not correctly aligned with the actual location (and maby a little bit to big)

I'm currently working to convert this into a HTML5 map but its taking a while because i never worked with maven/kotlin.

**Comment by PubgKnown** [comment]
Java is absolutely not the best language to have something like this running in especially in a VM.

That said I have a few tweaks I haven't pushed up yet. Like removing the 8k res tiles. Cuts the load time in half and isn't really necessary.

It would be nice to remove items when picked up though.

**Comment by boludo102938** [comment]
I am converting this to c# monogame.. not sure if it'll get faster..

**Comment by Dolajzis** [comment]
PubgKnown 
Just wanna say thanks for all your tweaks, I found them very helpful. Also big thumb up for author of this project. What a great job!

**Comment by blahblah53** [comment]
@PubgKnown i have tried to build your project and i get the .jar file but i will not open the original nuild works fine but not yours

**Comment by TheUserUnknown** [comment]
@boludo102938 If you are done converting it to C# Mongogame, could you make a repo for it? I would love to implement my HTML5 map

**Comment by brandont1** [comment]
Is there anyway someone could send me a link on how to get all this stuff built out and operational? I'm not sure where to start 

Thanks in advance for the help
