### ISSUE TITLE
How to get the arpspoof going on a windows pc?

### ISSUE THREAD

**Issue by Marv63** [AiYinZiLeGong/PUBG-Radar#32]

**Comment by Marv63** [comment]
I´m getting crazy with the arpspoof:
first i thought i could use the dsniff from here: http://www.datanerds.net/~mike/dsniff.html
then the .exe files did nothing and i wasn´t able to type in smth.
then i searched for 2 hours for a arp spoofing extention since all the ARP spoof tools just break the internet or simply crash. There is nothing new about arpspoofing so i stopped at page 10 of google searching and wrote this. 
How did you guys did this on a windows PC
Hope you can help because im about to surrender

**Comment by Norxy** [comment]
From JurishCrypter on another issue

"The simplest way I can instruct:
Download arpspoof from the github link kajaaaka gave, download maven for windows, extract them to individual folders, add those folders with their binary executable to the system variable path, execute arpspoof as instructed in readme, make sure your gaming computer has winpcap (so windows winsock packets can be read as udp, tcp, arp) and simply compile and execute the jar."

https://github.com/alandau/arpspoof

**Comment by Marv63** [comment]
Thank you wth did it not came up on Google 🤦‍♂️
Spoofer works I compiled it correctly but it throws up an error at my middle pc when I execute the pubg-radar-with-dependencies.jar it says: couldn't find the main class: pubg.radar.gameKt. Program will exit. 
But when I go to classes/pubg/radar there is a gameKt.class file,  so where's the problem???
Here is how I compiled it:
I did: "mvn install"  In the pubg radar folder, then I ran: "nvm compiler:compile" then it made the target folder and everything looked quite normal (no errors or warnings) 
Should it be compiled differently?
Jesus christ I spend 5 hours now onto this 😂

**Comment by kajaaakaka** [comment]
Just do "mvn package"

**Comment by Marv63** [comment]
Ok thank you will try It tomorrow

**Comment by Marv63** [comment]
Ok I deleted the whole folder and extracted the zip again (so there is nothing from before) and did nvm package. I still got the previous error: couldn't find the main class: pubg.radar.gameKt. Program will exit.
I run windows Vista with Java installed can't find the mistake

**Comment by Marv63** [comment]
I try updating Java now

**Comment by Marv63** [comment]
Not working

**Comment by Marv63** [comment]
Ok I got the network selection thing showing up, but when I selected a network: simply nothing show up just 2sec the loading mouse and then nothing happens(no errors etc) . How can I fix this or can I view a log or smth because. I didn't found anything like this.
Specs: windows vista 32 bit, jre 1.8_161 (cpu/ram is at 10%/5%when I start it and goes down very fast again. Wireshark receives packages.
I'm confused. 
Now I try putting a vm with Ubuntu on the laptop and see if it works🙄

**Comment by Norxy** [comment]
Use the linux version, you need to use it in cmd w/ admin rights : java -jar "radar.jar" middleman_ip PortFilter|PPTPFilter gamingpc_ip

**Comment by Marv63** [comment]
Hello
I came to the result that it's not pussible to run this on a 32-bit computer I tried it on Vista 32 bit, Ubuntu 16 32bit and Linux 4.15 32bit everywhere the same issue after long tweaking you get the error that:
LWJGL3(which is used here)  is only for 64 bit / missing (I linked it correctly when compiling(worked on my gaming computer) and I bounded the library manualy with:                  
 -Dorg.lwjgl.librarypath:lwjglpath (when possible))   or too old (because missing functions when you try lwjgl1/2 (when you change all the settings variables for lwjgl 1/2)<-probably I didn't change all, but now I don't have time for experimentation anymore. Anyways, it was fun.)
Ps: thx for the help :)
