### ISSUE TITLE
Test using pcap files

### ISSUE THREAD

**Issue by boludo102938** [AiYinZiLeGong/PUBG-Radar#33]
So I'm experimenting some things and wanna to test it offline. I recorded a match using windump and I'm using it with the offline sniffing method present in the sniffer class.

The problem is that by doing this I get alot of out of bounds exception thrown by the readbit method and the whole things just don't work. 

I'm wondering if anyone know what's going on? Are the order of the packets different when recording? Or something changes in the pcap file?

**Comment by boludo102938** [comment]
Looks like using tcpdump on Linux produces a better result tha  windump on Windows and it seems to work better, but still many throws from the buffer.

**Comment by alangregory** [comment]
Use wireshark, and export as tcpdump format
