### ISSUE TITLE
setup guide - newbie

### ISSUE THREAD

**Issue by kek777** [AiYinZiLeGong/PUBG-Radar#34]
hello guys, can anyone teach me to setup this pubg radar? thanks in advance :)

**Comment by Norxy** [comment]
From JurishCrypter on another issue

"The simplest way I can instruct:
Download arpspoof from the github link kajaaaka gave, download maven for windows, extract them to individual folders, add those folders with their binary executable to the system variable path, execute arpspoof as instructed in readme, make sure your gaming computer has winpcap (so windows winsock packets can be read as udp, tcp, arp) and simply compile and execute the jar."

https://github.com/alandau/arpspoof


If you're using a VM in the gaming PC, just use it in bridge mode and use the one in master branch

**Comment by GWONGI0830** [comment]
Can I remotely control with Skype?

**Comment by kek777** [comment]
@Norxy Thanks for the guide. Will try it later. :)
