### ISSUE TITLE
RenderBadPicture?

### ISSUE THREAD

**Issue by N1teW0lf** [AiYinZiLeGong/PUBG-Radar#35]
when i run sudo java -jar pubg-radar-with-dependencies.jar <middle_pc_ip> <PortFilter|PPTPFilter> <game_pc_ip>
i get :
Error of failed request: RenderBadPicture (invalid picture parameter)
Major opcode of failed request: 139 (RENDER)
Minor opcode of failed request: 7 (RenderFreePicture)
Picture id in failed request: 0x120003c
Serial Number of failed request: 689
Current serial number in output stream: 692
AL lib: (EE) alc_cleanup: 1 device not closed

Need some help with this.

**Comment by kapiwulon** [comment]
are you blind?  
![image](https://user-images.githubusercontent.com/12907074/36323537-8d788f58-1351-11e8-9826-6436c3cdc106.png)

**Comment by N1teW0lf** [comment]
lmao guess i am haha, went past it a million times, ill just step back and take that L lol

**Comment by Cron5** [comment]
Same error here. Ubuntu 17.10.1. 
- PC with the game ip 192.168.1.35
- laptop Ubuntu ip 192.168.1.37
- Router ip 192.168.1.1

Im using the following parameters to run:
- sudo arpspoof -i enp8s0 -t 192.168.1.35 192.168.1.1
- sudo arpspoof -i enp8s0 -t 192.168.1.1 192.168.1.35
- sudo java -jar pubg-radar-with-dependencies.jar 192.168.1.37 PortFilter 192.168.1.35

When im running the radar a new window pops up, it let me choose network interface and near 192.168.1.37 i see "null"(im not shure what should i see there).
Any idea how to fix?
