### ISSUE TITLE
Errors when running the .jar file, help appreciated.

### ISSUE THREAD

**Issue by 1337jay** [AiYinZiLeGong/PUBG-Radar#36]
Hello,

I'm basically new to programming and stuff like this so please don't get upset if this is an easy fix or whatever, I'm still learning. Everything is setup, I run the two arpspoof commands and then when I want to run the .jar file I get the following error:

Error of failed request:  RenderBadPicture (invalid Picture parameter)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  7 (RenderFreePicture)
  Picture id in failed request: 0x460002b
  Serial number of failed request:  2649
  Current serial number in output stream:  2655
AL lib: (EE) alc_cleanup: 1 device not closed

Any help will be highly appreciated, thanks!

**Comment by Norxy** [comment]
"If you experienced X Error of failed request: RenderBadPicture (invalid Picture parameter) on Linux build, try switch to branch linux. Run with arguments <ip_to_sniff> <PortFilter|PPTPFilter> [target_ip]"

It's written on homepage, come on

**Comment by TheUserUnknown** [comment]
@Norxy People want to use cheats so badly they cant even read a simple README file lmao 📦
