### ISSUE TITLE
setup guide

### ISSUE THREAD

**Issue by GWONGI0830** [AiYinZiLeGong/PUBG-Radar#38]
I do not understand here. I am a newbie.
I want you to explain it easily.

run sudo arpspoof -i <eth_interface_name> -t <game_pc_ip> <router_ip> to spoof game pc.
run sudo arpspoof -i <eth_interface_name> -t <router_ip> <game_pc_ip> to spoof router.
run sudo java -jar pubg-radar-with-dependencies.jar <middle_pc_ip> <PortFilter|PPTPFilter> <game_pc_ip>

**Comment by alantody** [comment]
my problem is, how to run this comands in other pc with WIN10, anyone help her?

**Comment by Jacob10383** [comment]
My discord is Jacobean#5971 I can help you.
