### ISSUE TITLE
How to set up in other PC with WIN 10 (Newbie)

### ISSUE THREAD

**Issue by alantody** [AiYinZiLeGong/PUBG-Radar#39]
How to make radar work on a PC on the LAN?

What commands do I have to use in arpspoof?

**Comment by Dolajzis** [comment]
I recommend you to run it in VM (virtual machine) which i think is the easiset option. The best advice i have is you go through all posts here, read them and you will certainly be allright.

**Comment by Pochtidruid** [comment]
@Dolajzis how did you solve the problem with runing arpspoof? im used w7x64 n get an error in cmd "
arpspoof is not a win32 application".

**Comment by Dolajzis** [comment]
@Pochtidruid Did you run the command prompt as admin? Anyway you don't need arspoof on VM, just build the radar with maven and run depencies.jar through cmd (as admin).
