### ISSUE TITLE
Error: Could not find or load main class jar

### ISSUE THREAD

**Issue by spiridonovdavid** [AiYinZiLeGong/PUBG-Radar#40]
Sorry i`am newbie, but trying to make this works.
What i did
1) installed Ubuntu on my vmware
2) downloaded sources
3) installed maven
4) compiled sources with command "mvn install"
5) trying to run jar with terminal "java jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar"
and now i am stucked because i have an error:
"Error: Could not find or load main class jar"

What i`am doing wrong ?

**Comment by jrudio** [comment]
It looks like on number 5 you're missing a hyphen before `jar`. So it thinks you're trying to load a class called `jar` instead of telling it the location.

**Comment by spiridonovdavid** [comment]
You was right! Thx, so stupid mistake )))

**Comment by NatsumeZhang** [comment]
root@ubuntu:/home/natsume/Desktop# java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.137.7 PortFilter 192.168.137.1
Error: Could not find or load main class pubg.radar.GameKt

 I have added a hyphen， still doesn't work

**Comment by NatsumeZhang** [comment]
Win 10  64bit
Eclipse Mars
JDK 1.8
It came out to be <excute>problem , and I added <pluginManagemen>to surrround <plungins>， then build the soure and get the jar file, but it dosen't work and shows 'Could not find or load main class pubg.radar.GameKt', so I remove the<pluginManagement> and rebulid it , thnaks to god , I see the panle comes up , after running game, nothing show up
