### ISSUE TITLE
How to build With Maven

### ISSUE THREAD

**Issue by Jacob10383** [AiYinZiLeGong/PUBG-Radar#42]
How do I build or compile/turn the files into something that actually runs?

**Comment by zecjy** [comment]
install maven, go to your directory of the pubg radar and `mvn install`, Done

**Comment by Jacob10383** [comment]
When I do that and run it I get the RenderBadPicture error and if I use the linux branch I get a exception in thread main java.lang.exceptioninitlizaerError

**Comment by TheUserUnknown** [comment]
@Jacob10383 Please read the README file

**Comment by Jacob10383** [comment]
Yes I did and I’m saying what my issue is.

**Comment by Jacob10383** [comment]
Maybe because I’m not sure what to put for  PortFilter|PPTPFilter

**Comment by Jacob10383** [comment]
Ok I got it to work besides two things, I am not exactly sure what goes for <PortFilter|PPTPFilter> and secondly the radar is just all gray.
