### ISSUE TITLE
ARPSPOOF WINDOWS !

### ISSUE THREAD

**Issue by brunopayne** [AiYinZiLeGong/PUBG-Radar#44]
How run this commands windows ?

run sudo apt-get install dsniff to install arpspoof.
edit /etc/sysctl.conf. add/uncomment net.ipv4.ip_forward=1. save and run sudo sysctl -p to enable ip_forward.
run sudo arpspoof -i <eth_interface_name> -t <game_pc_ip> <router_ip> to spoof game pc.
run sudo arpspoof -i <eth_interface_name> -t <router_ip> <game_pc_ip> to spoof router.
run sudo java -jar pubg-radar-with-dependencies.jar <middle_pc_ip> <PortFilter|PPTPFilter> <game_pc_ip>

**Comment by M0rtale** [comment]
cd to the folder where arpspoof is contained on your middleman pc

then do "arpspoof.exe <gaming pc's IPV4>"

the middleman pc has to be connected to the same router as the gaming PC, sharing the same default gateway.

**Comment by brunopayne** [comment]
it works thanks, but my player stuck now on lobby, rest of players not

**Comment by brunopayne** [comment]
I changed the sniffer.kt file and now my player moves on radar, but now when I'm on the move it shows a black scratches on the map radar

**Comment by Dolajzis** [comment]
I'm runing this radar on the game pc. I tried to get this work on win10 and win7 laptops but all the time I get stuck with arpspoof. The thing is, i do the command, arpspoof start working and straight after that my gamepc's internet just stop working, no error nothing. Any idea to fix this?

**Comment by Dolajzis** [comment]
Of course I have arpspoof on my middle radar pc not on the game one. The only thing I have on my game pc is WinPcap. For now I'm running it on VM aswell but trying to get this work with second pc.
