### ISSUE TITLE
Not displaying map and not following my player

### ISSUE THREAD

**Issue by Jacob10383** [AiYinZiLeGong/PUBG-Radar#45]
I have two issues, the radar is just grey and does not display any map, and secondly I can see people on the radar and it works however it does not follow me and I have tried voice chat. Any ideas?

**Comment by Jerry1211** [comment]
https://github.com/AiYinZiLeGong/PUBG-Radar/issues/22

**Comment by Jacob10383** [comment]
Oh shoot my bad I scrolled through the previous issues but apparently did not see that one.
