### ISSUE TITLE
Build project maven

### ISSUE THREAD

**Issue by ikolka** [AiYinZiLeGong/PUBG-Radar#46]
I build the project in maven, what should I do?
![image](https://user-images.githubusercontent.com/36614703/36362365-05275436-1545-11e8-9bc1-9c450385f69e.png)
And how to open it later?

**Comment by Jacob10383** [comment]
Type cd then the directory of the radar folder, then do mvn install.  If you cannot fiqure it out msg me on discord Jacobean#5971

**Comment by hackmethod** [comment]
I am having issues as well.  Everything looks like it installs and builds but then at the end it says BUILD FAILURE...  I cant even run it. `sudo java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar <middle_pc_ip> PortFilter <game_pc_ip>` throws errors.  @Jacob10383 I have also tried adding you on discord but cannot seem to get DM working.  If you could DM me that would be great `incidrthreat#4219`
