### ISSUE TITLE
Hide items dots.

### ISSUE THREAD

**Issue by FrZ-BR** [AiYinZiLeGong/PUBG-Radar#47]
Hey guys, im using this project since the beginning great work.

in java is possible to create some hotkey to hide the items dots?

not expert in java... It's a pity that it's not in html5

**Comment by ikolka** [comment]
Hello,you can help me, for money
Please write me discord: Iko#6510

**Comment by Jerry1211** [comment]
@ikolka sent you a friend request

**Comment by ikolka** [comment]
@jerr1211 add me discord
