### ISSUE TITLE
Players don't show up at the end

### ISSUE THREAD

**Issue by Marv63** [AiYinZiLeGong/PUBG-Radar#48]
Hello, it's me again
I got it to work, but some players (especcially at the end) do not show up on map (I did use the updated sniffer.kt and I speak at the beginn

**Comment by Pochtidruid** [comment]
yeah, same problem to me

**Comment by Pochtidruid** [comment]
and when people, obviously, quickly enter the radar coverage area (1.5km) on transport at a speed of 100 km/h+ - they do not appear in it

**Comment by AiYinZiLeGong** [comment]
#10
