### ISSUE TITLE
DAMNCheaters... can we do the same?

### ISSUE THREAD

**Issue by FrZ-BR** [AiYinZiLeGong/PUBG-Radar#49]
Hello guys, 
I think everyone here wants to get the most out of this project. so thinking about it, I recently bought a Map-package from DAMNCheaters to see their implementations. 

it is clear from the first moment that they are using much of this project.

They already have:

- Hotkeys to hide items, ui and etc... **(check at the end)**
- Camera position **(not the player direction, how?)**
- Clear items names on the map **(check at the end)**
- when the item is collected it disappears from the map **(how?)**
- Players arrows **(how?)**

My question... 

All this is possible with java or they are using other type of language? my knowledge is only in html5.

Thanks.

![items_dc](https://user-images.githubusercontent.com/17305867/36391789-dbb50b74-1586-11e8-8f43-19d8e30abf37.png)
![ui_dc](https://user-images.githubusercontent.com/17305867/36391790-dbd7ed10-1586-11e8-838b-1b0f8194c25f.png)

**Comment by Jacob10383** [comment]
Yea I just have a snapshot of a vm that has that open so if it ever crashes or anything I just revert the snapshot and then I have the radar working again and I don’t gotta pay for it. But as far as how there’s works I don’t know other then the fact it uses winpcap and redirecting game pc traffic to vm.

**Comment by PubgKnown** [comment]
I am fairly certain most of this is possible to achieve. I believe they are parsing packets much better than what this repo is currently doing. Something someone can probably greatly improve upon. However that said I don't think java is the best language for this type of thing when your after good performance within a VM.

**Comment by FrZ-BR** [comment]
@Jacob10383 LoL thats rough solution my friend haha well done.

@PubgKnown Yeah i think they are using another language because its very light and well optimized.

**Comment by TheBlackGolem** [comment]
Hotkeys are not that difficult. Here's an example of mine:

![java_2018-02-23_17-29-52](https://user-images.githubusercontent.com/8807778/36604977-9b052c44-18bf-11e8-8fb9-52cf20349ab7.png)

I'm just rendering a few images and use the keyDown function of InputAdapter as follows:
```
override fun keyDown(keycode: Int): Boolean {
    when (keycode) {
        Input.Keys.F1 -> {
            //code...
        }
        Input.Keys.F2 -> {
            //code...
        }
    }
    return true
}
```

**Comment by solixa** [comment]
but how to catch these keys when the radar window does not have focus?

**Comment by TheBlackGolem** [comment]
In that case, I'd recommend you this library: https://github.com/kwhat/jnativehook

**Comment by solixa** [comment]
funny i was just googling and came across just this, thanks, new to kotlin, couldnt figure out using intellij how to bring in new dependencies :X

**Comment by AiYinZiLeGong** [comment]
#10 #2
