### ISSUE TITLE
Does not work on linux

### ISSUE THREAD

**Issue by Mykybo** [AiYinZiLeGong/PUBG-Radar#5]
First I get `Cannot save settings file to /root/.pubgradar/settings.properties` even though I run it as root and then I get:
```
6
6
6
7
2
0
0
0
0
0
X Error of failed request:  RenderBadPicture (invalid Picture parameter)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  7 (RenderFreePicture)
  Picture id in failed request: 0x560001a
  Serial number of failed request:  1093
  Current serial number in output stream:  1094
AL lib: (EE) alc_cleanup: 1 device not closed
```
and the program closes...

**Comment by AiYinZiLeGong** [comment]
try `Jdk 8u161/ 8u162`?

**Comment by Mykybo** [comment]
Updated jdk to `8u161-1~webupd8~0` from 151, still same error :b.
Java version: 
```
$# java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by Mykybo** [comment]
After updating to java 9:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.system.MemoryAccess (file:/path/to/PUBG-Radar/target/pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.lwjgl.system.MemoryAccess
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
X Error of failed request:  RenderBadPicture (invalid Picture parameter)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  7 (RenderFreePicture)
  Picture id in failed request: 0x560005d
  Serial number of failed request:  1488
  Current serial number in output stream:  1489
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by AiYinZiLeGong** [comment]
I have found the problem. It is Swing causing this error.

**Comment by AiYinZiLeGong** [comment]
I have removed Swing in the new branch `linux`. 
Using command line arguments to configure the network interface:
`sudo java -jar pubg-radar.jar 192.168.1.123 PortFilter`
`sudo java -jar pubg-radar.jar 192.168.1.123 PPTPFilter`

**Comment by Mykybo** [comment]
```
# ./pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.0.14 PortFilter 192.168.9.16
6
6
6
6
7
0
0
0
0
0
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:46)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:209)
```
If I switch the ips (192.168.0.16 PortFilter 192.168.9.14) then the program starts, but stays gray.
wireshark:
![wire-pubg](https://user-images.githubusercontent.com/9023791/35843439-7832603e-0b08-11e8-9f68-ff2b1b041e35.png)

I have setup OpenVpn server on linux, routing traffic through it from windows. Do I have the source/dest right? I am not sure what filter to use (PortFilter/PPTPFilter)

**Comment by AiYinZiLeGong** [comment]
I have only parsed PPTP protocol, so OpenVPN may not be supported currently.

**Comment by AiYinZiLeGong** [comment]
I am able to separate sniffing from game using `arpspoof`.

**Comment by Mykybo** [comment]
So I have setup a PPTP tunnel instead:
![wire-pubg-pptp](https://user-images.githubusercontent.com/9023791/35879224-f4f339e6-0b7a-11e8-8ab6-0aebcae03445.png)
And run the program with:
`sudo ./pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.0.16 PPTPFilter 192.168.0.14`
The program starts, but stays grey (and no error in console).

**Comment by AiYinZiLeGong** [comment]
I only implement the [PPTP GRE Packet](https://en.wikipedia.org/wiki/Generic_Routing_Encapsulation). Please make sure the protocol is right.
Or you have to implement your own protocol parser.

**Comment by AiYinZiLeGong** [comment]
Yours seem like PPP Compressed? Maybe try uncompressed one?

**Comment by whtiehack** [comment]
I think we also need to implement the protocol([L2TP](https://en.wikipedia.org/wiki/Layer_2_Tunneling_Protocol)).
I'll try later.

**Comment by akiskourtis** [comment]
Just my 2 cents, the interface also needed to be set to promisc mode explicitly through ifconfig, then it worked.

**Comment by AiYinZiLeGong** [comment]
@akiskourtis you're right. I update the code.
