### ISSUE TITLE
Is there any way we can extend radius of item detection?

### ISSUE THREAD

**Issue by lonelytb** [AiYinZiLeGong/PUBG-Radar#54]
We have to be close enough to buildings (150 meters radius maybe?) to detect if there are items.
Is there any way to extend the radius?

**Comment by Pochtidruid** [comment]
Also items are not always displayed, in 1-st game i see on radar a kar, next game - nope

**Comment by mjmfighter** [comment]
You won't be able to extend the range. PUBG only sends you the items that are close to your proximity
