### ISSUE TITLE
Need some tips

### ISSUE THREAD

**Issue by Pochtidruid** [AiYinZiLeGong/PUBG-Radar#55]
![tips](https://user-images.githubusercontent.com/36651692/36455393-e2ff844c-16b0-11e8-9bae-f791847798a3.jpg)

Using compilation of TheUserUnknown's fork.
1) what is this phantom marks on the radar at number 1 on the pic?
2) what do the counter at number 2 on the pic?
3) why is downloading speed drops from 10mb/s to 200 kb/s n discord lagging "like hell" while spoofing, how to fix it?
4) in the last few laps people are not displayed at all on radar, or just in last game on last laps 10 ppl alive but on radar just 5 or 6, how to fix it?
and when ppl, obviously, quickly enter the radar coverage area (1.5km) on transport at a speed of 100 km/h+ - they do not appear in it, i mean they are near to you, but not displayed on radar
5) for what is an sound allert used? 
it seems to me he is procs some kind of random.
6) TheUserUnknown as default/AiYinZiLeGong with additions forks work fine for me, but 
compilation of PubgKnown fork - runs without errors, everything is fine, but .jar does not start, and his radar after comp is bigger then original by the 80 mb, it is because of the loot images added?

I apologize for the incorrect construction of proposals

**Comment by lonelytb** [comment]
1. parachute
2. processing of player statistics gathering, 2 completed / 88 pending 
3. cant fix, or very hard to fix. coz it's arp spoof
4. idk
5. 1 min warning of circle
6. idk

**Comment by Pochtidruid** [comment]
@lonelytb r u sure that the problem is in arpspoof? i mean if the radar is launched from under VM then there is no such problem with the display of players at the end?

**Comment by PubgKnown** [comment]
The reason my fork compiles larger is because I render the map in tiles similar to google maps. I even have 8k tiles in the resources folder but they are commented out by default to keep memory usage low because it does cause a performance hit keeping all the 8k tiles in memory. I just haven't removed them from the repo so they still get put in the final build file.

**Comment by Pochtidruid** [comment]
@PubgKnown yep, i already understand it, now ur fork is work perfectly, thx you for attention
