### ISSUE TITLE
Problen compile

### ISSUE THREAD

**Issue by leshoi** [AiYinZiLeGong/PUBG-Radar#57]
![default](https://user-images.githubusercontent.com/36703391/36490958-021aae50-1743-11e8-878c-e3522c5d6fea.png)
Run as administrator and still have access problem

**Comment by Pochtidruid** [comment]
Не изобретай велосипед, просто запусти .jar через даблклик мышкой.

**Comment by manzanita0412** [comment]
You're not in the same directory as the .jar file you're trying to execute. Either run that in the right directory or give it the right path to the .jar

**Comment by leshoi** [comment]
Как я запущу .jar даблкликом если я даже не могу его откомпилить? я только поставил maven  и все дальше он ниче не хочет делать(java , maven все работает) он просто не компилирует

**Comment by Sir3x** [comment]
А как пытался компилировать ?

**Comment by leshoi** [comment]
Да в том то и дело я не могу найти как его откомпилировать тут гайд только по запуску как скомпилировать данный софт я ни слова не нашел

**Comment by Sir3x** [comment]
Ну там же написано -use MAVEN 
https://maven.apache.org/guides/getting-started/

Ну а по быстрому - mvn compile, mvn package

**Comment by leshoi** [comment]
Ну теперь другая проблема все откомпилилось , нужный мне файл нашел с расширением .jar но через утилиту java он не открывается как и через cmd до этого пиздец убогий язык

**Comment by leshoi** [comment]
Ну все я сделал вроде правильно , откомпилил , установил wincap , прописываю командую строку он ее исполняет и ниче не происходит(никаких ошибок) просто просит ввести еще команду следующую

**Comment by Pochtidruid** [comment]
@Sir3x херню советуешь
@leshoi просто ВНИМАТЕЛЬНО посмотри остальные обсуждения по форку в т.ч закрытые, ты не указал правильный путь, ты юзаешь не тот синтаксис

**Comment by Sir3x** [comment]
@Pochtidruid Можешь обосновать ?

**Comment by Pochtidruid** [comment]
@Sir3x конкретно из под win "mvn compile, mvn package" не применяются, а он сидит на 10-ке

**Comment by Pochtidruid** [comment]
короче @leshoi все твои ответы тут [https://github.com/AiYinZiLeGong/PUBG-Radar/issues/46](url)

**Comment by frendyd** [comment]
![default](https://user-images.githubusercontent.com/36714006/36506051-7dd66692-1766-11e8-9f37-4bf3035229db.PNG)
what is this ?:(

**Comment by Pochtidruid** [comment]
@frendyd update jdk & jre, install maven - u dont have correct libraries
