### ISSUE TITLE
Problem middle pc setup

### ISSUE THREAD

**Issue by Vladimir9991** [AiYinZiLeGong/PUBG-Radar#58]
The guys launched on the gaming PC, everything works great! Can someone help with the launch on a laptop? And then Alt+tab constantly is not convenient... I will be admirable! I tried using the command " java-jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar "IP laptop" PortFilter " IP game computer"
gray screen... <a target="_blank" href="https://radikal.ru"><img src="https://d.radikal.ru/d12/1802/de/a1371db0b1f6.png" /></a>

**Comment by Pochtidruid** [comment]
читай прошлые обсуждения, все разжевано.

**Comment by Vladimir9991** [comment]
Носом ткни плез))

**Comment by Pochtidruid** [comment]
@Vladimir9991 с этим [#57](https://github.com/AiYinZiLeGong/PUBG-Radar/issues/57) вы не братья? точно такая же тема, в ней есть решение твоей проблемы

**Comment by Vladimir9991** [comment]
Ты читать умеешь я написал что я запустил все как положенно на игровом компе все работает!!!!! не работает на ноутбуке!!!! потомучто там надо подменять айпишники как я понял... Если у тебя проблемы с глазами пройди мимо!!!

**Comment by Norxy** [comment]
English please guys? I am in the same situation
