### ISSUE TITLE
Dont opens jar 

### ISSUE THREAD

**Issue by vladimir2412** [AiYinZiLeGong/PUBG-Radar#59]
Hello today i want to tell you about my problem. 
I install this cheat and i cant open fille .jar.

**Comment by Norxy** [comment]
What do you mean by "I install this cheat"?
What have you done exactly and how do you open it? What OS are you using

**Comment by vladimir2412** [comment]
8.1 
windows

**Comment by vladimir2412** [comment]
after packaging filles i try to open .jar but its dont open

**Comment by vladimir2412** [comment]
i dont dowland winpcap 
its can be problem?

**Comment by vladimir2412** [comment]
I'm just dont dowland winpcap when i dowland its works!

**Comment by vladimir2412** [comment]
<close>

**Comment by vladimir2412** [comment]
close
