### ISSUE TITLE
Compiled .Jar dosent seem to work {Plz Help To Verify}

### ISSUE THREAD

**Issue by GreenRanger2478** [AiYinZiLeGong/PUBG-Radar#60]
Hey Guys!
First thanks to the author for this source i am trying to make it work and kinda stuck now. I was able to successfully build the source with Maven using the "mvn install" command. However after compiling when i test the .jar file this error shows up which i cant pin on what the problem is.

Error = https://imgur.com/a/Wwg6g

Would be very grateful form some help as i am a complete noob with Kotlin

**Comment by al1m3rt** [comment]
did u change any code

**Comment by vladimir2412** [comment]
you are stupid? u must open u filder where radar click shift+right click mouse and then window commands. Then cmd opening and u must write mvn package.

**Comment by Norxy** [comment]
He already did that, don't tell someone he's stupid if you can't even read.

If you changed something try to remove it, if it's the original, try compiling the one in linux branch

**Comment by GreenRanger2478** [comment]
I have tried multiple times to fix this on multiple computers. I am using java 9 form both the jdk and jre. I have changed nothing in the code, i am just trying to make it work before i set up the vms and such. I have attached another image of the compiling process this might help point out something i have missed.
![complied](https://user-images.githubusercontent.com/36716121/36543124-e480ec0e-17f3-11e8-8445-a5d757d01f2c.jpg)

**Comment by Norxy** [comment]
The usage is middleman/vm ip <option> gaming_ip

If it still doesn't work, I can help you with teamviewer

**Comment by GreenRanger2478** [comment]
Yea i tried that it doesn't work every time i get this error which i cant seem to fix. so from the images can anyone verify that I complied the source correctly?

**Comment by jrudio** [comment]
This is a guess, but the error sounds like it has trouble trying to find the network interfaces. The `can't obtain static method fromNative` sounds like you compiled it on a different machine/os (say linux) and are trying to run it on a another (say windows). If that's not the case, then my apologies lol.

**Comment by GreenRanger2478** [comment]
So here is the thing i gave up on windows and loaded a VM with Ubuntu 17.10 recompiled the source and everything. And ran it now this errors occurs if anyone knows how to fix it i will be very thankful.
![2018-02-23 00_14_18-ubuntu 64-bit - vmware workstation 12 player non-commercial use only](https://user-images.githubusercontent.com/36716121/36568961-f62a41f0-183c-11e8-9804-7a89a05e54f6.png)

**Comment by Norxy** [comment]
Install VMWare tools it will works after
