### ISSUE TITLE
crashing in vm

### ISSUE THREAD

**Issue by al1m3rt** [AiYinZiLeGong/PUBG-Radar#61]
it crashes every 10 - 20 minutes. i think its because of shitty java. do you get this problem also? do you think systems with better hardware would run smoother? maybe with more ram?

**Comment by Sir3x** [comment]
What OS you use as guest OS?

**Comment by al1m3rt** [comment]
win 7 32 bit

**Comment by Sir3x** [comment]
Try to increase RAM amount for Guest OS.

**Comment by al1m3rt** [comment]
it still crashes at 1 gb

**Comment by al1m3rt** [comment]
what is yours set at?

**Comment by al1m3rt** [comment]
up

**Comment by al1m3rt** [comment]
any idea?

**Comment by al1m3rt** [comment]
i cant be the only one with this issue
