### ISSUE TITLE
arpspoof lagging issues

### ISSUE THREAD

**Issue by TSecretT** [AiYinZiLeGong/PUBG-Radar#63]
Hey guys. I have laptop (Wifi) and PC (Lan) connected to each other with arpspoof. During that connection my speed drops significantly and sometimes i am having lags in pubg (every 3-5 second im getting teleported a few steps back)

I have found solution in https://github.com/AiYinZiLeGong/PUBG-Radar/issues/51(url)
But it seems like not helping me.
Thanks!

**Comment by Pochtidruid** [comment]
problem just in ur router or u do something wrong

**Comment by noise87** [comment]
do u active ipv4 forward?

**Comment by Pochtidruid** [comment]
@noise87 i think yea if #51 not helping him

**Comment by niklaswi7** [comment]
Running the VPN solution or arpspoof? If you are running arpspoof try and do a ping before arpspoof is started and while its running to check if you have done the ip routing like you should do.
