### ISSUE TITLE
map not show

### ISSUE THREAD

**Issue by pateutz** [AiYinZiLeGong/PUBG-Radar#64]
![asdasd](https://user-images.githubusercontent.com/9793846/36546116-369e33f8-17f3-11e8-8963-c4fc2d6bc2df.jpg)

Why it not show the map ?

**Comment by Pochtidruid** [comment]
cmon, seek solutions in other issues[#43](https://github.com/AiYinZiLeGong/PUBG-Radar/issues/43)

**Comment by Seroka** [comment]
try this #22

**Comment by pateutz1** [comment]
fixed with #22 thank you.
