### ISSUE TITLE
amd/ati gl3 problem

### ISSUE THREAD

**Issue by pateutz1** [AiYinZiLeGong/PUBG-Radar#68]
AMD/ATI drivers

cmd output:

> Exception in thread "main" java.lang.IllegalArgumentException: Error compiling s
> hader: Vertex shader
> Vertex shader failed to compile with the following errors:
> ERROR: error(#272) Implicit version number 110 not supported by GL3 forward comp
> atible context
> ERROR: error(#273) 1 compilation errors.  No code generated
> 
> Fragment shader:
> Fragment shader failed to compile with the following errors:
> ERROR: error(#272) Implicit version number 110 not supported by GL3 forward comp
> atible context
> ERROR: error(#273) 1 compilation errors.  No code generated
> 
> 
>         at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteB
> atch.java:161)
>         at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:124
> )
>         at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:78)
> 
>         at pubg.radar.ui.GLMap.create(GLMap.kt:142)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjg
> l3Window.java:416)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.jav
> a:364)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Applica
> tion.java:136)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Appli
> cation.java:110)
>         at pubg.radar.ui.GLMap.show(GLMap.kt:97)
>         at pubg.radar.GameKt.main(Game.kt:43)

if i modify this in GLMap.tk

> config.useOpenGL3(false, 0, 0)

is working but now i need to test it to see if all good

**Comment by pateutz** [comment]
yea it work with opengl3 off but is a bit worst

**Comment by ReddeR1337** [comment]
Isn't helping for me :(

**Comment by pateutz** [comment]
with opngl off will not show a lot of things so, first of all you need use a new graphic card i think xD
