### ISSUE TITLE
Error after running compiled program.

### ISSUE THREAD

**Issue by Glidark** [AiYinZiLeGong/PUBG-Radar#70]
I am currently running virtualbox with debian installed, i have a bridged adaptor and i am arpspoofing. 
I get a grey screen when running the jar with the following command:

java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.2.212 PortFilter 192.168.2.1
192.168.2.1 being the router and .... 212 being the gaming pc.
What is weird is im getting an error that seems to responsible for drawing the map, but i still get the "map window". idk maybe you guys can help with your expertise

`[LWJGL] GLFW_PLATFORM_ERROR error
	Description : X11: RandR gamma ramp support seems broken
	Stacktrace  :
		org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:695)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:80)
		com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:87)
		pubg.radar.ui.GLMap.show(GLMap.kt:97)
		pubg.radar.GameKt.main(Game.kt:49)

`

**Comment by Jerry1211** [comment]
you need to install the accelerated graphics driver for your virtual machine, for Vmware Workstation its Vmware Tools.
