### ISSUE TITLE
middle pc \w arpspoof.exe

### ISSUE THREAD

**Issue by ReddeR1337** [AiYinZiLeGong/PUBG-Radar#73]
I have gaming pc and laptop (both enebled in the same router "tp-link123idk")
I install winpcap on both pc< install java on laptop, and use https://github.com/alandau/arpspoof
run arpspoof.exe with gaming ip `arpspoof.exe 192.168.0.102`
And get this:
![p2gw5ga](https://user-images.githubusercontent.com/11780299/36623533-a5222c7a-1916-11e8-9c60-e4231f287735.png)
Idk fine is it but go to next step
I try to run jar `java -jar PUBG-RADAR-1.0.jar "192.168.0.104" "PortFilter" "192.168.0.102"`
192.168.0.102 -  is gaming pc
192.168.0.104 - is laptop
And get this:
![image](https://user-images.githubusercontent.com/11780299/36623613-4150c480-1917-11e8-9ed9-22b874d4abc2.png)
Next step I choose PPTPFilter and radar run but i dont see nothing
![image](https://user-images.githubusercontent.com/11780299/36623635-6eeac922-1917-11e8-9486-89342776a3e8.png)

Any ideas how to fix that ?
I read many issues but dont see any tutorial for dumb like me xd

**Comment by Pochtidruid** [comment]
1) u can use command without ""
java -jar PUBG-RADAR-1.0.jar 192.168.0.104 PortFilter 192.168.0.102
2) [#21](https://github.com/AiYinZiLeGong/PUBG-Radar/pull/21)

**Comment by ReddeR1337** [comment]
@Pochtidruid 
http://keepthetech.com/2016/01/enable-ip-routing-on-windows10.html
Как эта хуета на русском называется ?
Служба маршрутизации и удаленного доступа по идеи но ее нету -_-
![image](https://user-images.githubusercontent.com/11780299/36624669-1638b968-1923-11e8-87c7-596611a4f64f.png)
Ебал рот, у тебя связь есть какая то другая, что бы быстрее как то с тобой общаться, я вроде не тупой и пытаюсь другие топики копать но все равно не одупляю как пофиксить то что у меня не рисует не чего
То ли сниф пакетов не работает, толе из за воутинга не работает...

**Comment by ReddeR1337** [comment]
По проводу не канало за то через wifi ноут сразу завелся 
закрыто, гигантское спасибо что носом ткнул

**Comment by brutalsam96** [comment]
@ReddeR1337 Did you notice very high spikes on latency ? On overall latency between pc and router.
I tested from my both pcs after you run arpspoof there is a huge latency spikes, rendering the game unplayable

**Comment by ReddeR1337** [comment]
@brutalsam96 Try this version https://github.com/Jerry1211/PUBG-Radar
On VMWare u can dont use arpspoof
Run radar an play

**Comment by Pochtidruid** [comment]
@brutalsam96 just fix like this #51

**Comment by brutalsam96** [comment]
@Pochtidruid So i have configured ip routing as in tutorial, but it is still lagging, on my gaming pc, while it works fine on middle pc (if try to spoof middle pc ip using gaming pc, but it's not working backwards) i tried enabling on both pcs, i tried enabling on each, still the same results, both pcs run windows 10

**Comment by 305634336** [comment]
My English is not very good, PUBG radar I do not know how to use, can you tell me?

**Comment by hamstler** [comment]
@ReddeR1337 Hello, im using Oracle VM VirtualBox with ubuntu installed on it.
I had same problem with gray map not showing anything.
Did evrything from topic i mean evry command.
While using on my game pc without any VM etc. it was good, i started jar while in menu, got gray window, when enter into match i was able to see map and after cliking T (VOIP) i was able see my movement etc.

Where should i start to find solution ?
