### ISSUE TITLE
This is public now

### ISSUE THREAD

**Issue by qqwtt** [AiYinZiLeGong/PUBG-Radar#74]
Repo, compiled .jars and fork repo links are available on public cheat forum.
I urgely recommend you to make your repos private or delete them as blueasshole are monitoring these forums and adding signatures to BattleEye.

**Comment by al1m3rt** [comment]
agree

**Comment by qqwtt** [comment]
On 3 forums to be exact.

**Comment by SamuelNZ** [comment]
Contribute or fuck off.

Good lucking sigging a jar file running in a VM. 

Fucking retard.

**Comment by SamuelNZ** [comment]
Wow just for future reference guys since your both brand new accounts, Github issues aren't a place for you to have a cry. This can't be detected by BE if you use another computer, period.

Good luck sigging kotlin running in a JVM.

**Comment by SamuelNZ** [comment]
Wow just for future reference guys since you're both brand new accounts, Github issues aren't a place for you to have a cry. 

This can't be detected by BE if you use another computer and good luck sigging kotlin running in a JVM for people who can't be bothered with all that.

**Comment by niklaswi7** [comment]
This is dumb, they cant scan a second pc and since your main pc aint doing anything wrong what are they gonna figure out with BE? Either you are dumb or just very bad a trolling either way please read up on what this does.
