### ISSUE TITLE
win7 32 bit or 64 bit?

### ISSUE THREAD

**Issue by al1m3rt** [AiYinZiLeGong/PUBG-Radar#77]
i use win7 32bit windows on my guest and java crashes per 20 minutes. should i upgrade to 64bit or its something else?

**Comment by Pochtidruid** [comment]
update to win10 x64.

**Comment by SamuelNZ** [comment]
Windows 10 x64 - 1709 seems to work best in a VM.

**Comment by Marv63** [comment]
@pochtidruid lol Update from x32 to x64 haha

**Comment by al1m3rt** [comment]
what about ubuntu?

**Comment by Marv63** [comment]
@al1m3rt there is no x32 lwjgl for Linux aviable for x64 should work
