### ISSUE TITLE
Map doesn't display

### ISSUE THREAD

**Issue by gideros8192** [AiYinZiLeGong/PUBG-Radar#8]
Hi,

Thanks for your great work. Btw, I cannot make the map to display. The only thing I can see is gray blank window. 
And, is it correct to run SNAPSHOT-jar-with-dependencies.jar? I cannot run these others because of error: No main manifest attribute. 
Pardon me since I am not familier with Java and related thing.

**Comment by Johnny112233** [comment]
Could you please tell us how you fixed the problem? I have the same issue with the gray screen although wireshark is getting game data :(
Please tell us how you fixed it
