### ISSUE TITLE
PPTPFilter mode does not work 

### ISSUE THREAD

**Issue by Ar2oria** [AiYinZiLeGong/PUBG-Radar#80]
hi, how to use the radar with option pptpfilter mode?
such as, my gamepc'c local ip is 192.168.0.100,  VPN(pptp)  ip is 192.168.0.150. the middle pc's local ip is 192.168.0.200
how to set the arpspoof and radar?
i tried to open arpspoof in cmd : <arpspoof's absolute path> 192.168.0.100
and radar in cmd : java -jar <radar's absolute path> 192.168.0.200 PPTPFilter 192.168.0.100.
however, it does not work.
sorry for my english.

**Comment by Ar2oria** [comment]
@AiYinZiLeGong , how to works with VPN?

**Comment by niklaswi7** [comment]
If you are running VPN why are you running arpspoof? Thats not how Arpspoof works.

**Comment by Ar2oria** [comment]
@niklaswi7  sorry , in the fact , i'm a newbie .... could u you tell me exactly how  to do in the PPTPFilter mode?  
if i use PPTPFilter to connect the radar , i can't run the arpspoof in the middle pc, i only need to run the radar in game pc, right?

**Comment by niklaswi7** [comment]
Read all the issues even the closed ones. If you are a newbie you will learn how to do it.

**Comment by Ar2oria** [comment]
@niklaswi7  all right, thanks again for your reply. i try to find the answer now.

**Comment by Ar2oria** [comment]
@niklaswi7  thk again，i have solved this problem and i modified some code in sniffer，now it can works in L2TP vpn mode.
