### ISSUE TITLE
Arpspoof  Problem

### ISSUE THREAD

**Issue by whitewingz2017** [AiYinZiLeGong/PUBG-Radar#85]
Hello I have problem with arpspoof on targeting.

this is my detailes
game_pc_ip: 192.168.1.2
middle_pc_ip: 192.168.1.5
gateway_ip : 192.168.1.1

already enabled Routing and remote access(automaticaly)

but when i type command 
arpspoof.exe 192.168.1.2

the result is:
Resolving victim and target..
Can't resolve victim IP, is it up?

so what did I miss?

Thanks in advance.

**Comment by XvenDeR** [comment]
Same for me.

**Comment by niklaswi7** [comment]
windows or linux?

**Comment by XvenDeR** [comment]
Windows, tried on other VM it worked, but only once... Still no idea why?

**Comment by niklaswi7** [comment]
litterally just do 
cmd -> run as admin -> cd to your arpspoof.exe -> arpspoof.exe 192.xxx.x.x (gamePC)
Should work

**Comment by whitewingz2017** [comment]
> litterally just do
cmd -> run as admin -> cd to your arpspoof.exe -> arpspoof.exe 192.xxx.x.x (gamePC)
Should work

same as result.

**Comment by niklaswi7** [comment]
Bridge connection? if running VM

**Comment by XvenDeR** [comment]
Bridge...

**Comment by XvenDeR** [comment]
Why it cant resolve gaming pc even if using same gateway...?

**Comment by NatsumeZhang** [comment]
![image](https://user-images.githubusercontent.com/16576667/36849859-1d53b276-1da0-11e8-990b-4c7043784cbf.png)
same problem as you ,
I use WIFI instead of ethnet, cauz' it's out of work, should this cause the problem?

**Comment by GoodMEHT** [comment]
NatsumeZhang, is it your local ip?

**Comment by NatsumeZhang** [comment]
@GoodMEHT  Yes,  finally I found the answer. Because I didn't share WIFI with VM , so I can't get any other machine in LAN.
