### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by kidd8250** [AiYinZiLeGong/PUBG-Radar#87]
Hi,AiYinZiLeGong.i wonder what verion of maven didi u use,and the JDK version. I'm using the maven 3.2.5 JDK1.7，compile error.

**Comment by niklaswi7** [comment]
Writing the error will help, but read the issues im pretty sure you will figure it out.

**Comment by kidd8250** [comment]
![image](https://user-images.githubusercontent.com/22736710/36770163-b313c6ac-1c83-11e8-9840-cb634f919908.png)
THIS IS THE ERROR, THANK YOU

**Comment by niklaswi7** [comment]
try using jetbrains or eclipse to compile it instend see if that fixes it, remember to get the kotlin addons from eclipse. 

If you have no idea how it works google it, its easy

**Comment by kidd8250** [comment]
Thank you . i will try
