### ISSUE TITLE
New features?

### ISSUE THREAD

**Issue by TrynCatchMeh** [AiYinZiLeGong/PUBG-Radar#89]
Hey, Not really an issue as much as a request wasn't sure where to put it, Would it at all be possible to put like what weapon the enemy has or are using, As well as I have seen other RADAR hacks have Health of the enemy, Perhaps when make it have a radar on the top of the file showing the position instead of the square box in the middle, Or even tell exact coordinate locations of players by there names, Not entirely sure if any of it is possible (Beside the health one) just a thought.

**Comment by AiYinZiLeGong** [comment]
0547113ab0a473fa54ecb5789a933d3d69b56317
