### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by boludo123215** [AiYinZiLeGong/PUBG-Radar#9]
All I get is a gray window, no map displayed.

I'm running it in a VM in bridge mode. Promiscuous mode enabled.
I can see the PUBG packets using "tcpdump" on linux

I'm using the linux branch and using the command line: 
sudo java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar 192.168.2.26 PortFilter 192.168.2.25

192.168.2.26 is linux guest ip
192.168.2.25 is windows host ip

Any Ideas?

**Comment by Johnny112233** [comment]
Hey,
same for me. Only agl gray screen after chosing the network.

I am receiving the packets with wireshark though. I hope the dev can help us. I dont even know if the reason are missjng packets or maybe some missing map data/ graphics driver problem or whatever. Please help us!

**Comment by whtiehack** [comment]
Did you use a VPN?If used, do not use the first try.
