### ISSUE TITLE
frame drop

### ISSUE THREAD

**Issue by noise87** [AiYinZiLeGong/PUBG-Radar#92]
hi, i noticed that with the map loaded in lunus (vmware) pubg has several frame drop, from 140+ to 20 or even less. without a loaded map it should be smooth. is there any fix for this thing? (replay and deathcam already disabled)

**Comment by al1m3rt** [comment]
buy better cpu :(

**Comment by noise87** [comment]
i7 7700 :/ 16gb ram and 1070, i don't think is a cpu problem

**Comment by caoliu1118** [comment]
delete 8k map
