### ISSUE TITLE
Few of us have been collectively modifying this radar check it out

### ISSUE THREAD

**Issue by Jerry1211** [AiYinZiLeGong/PUBG-Radar#94]
Check out.
https://github.com/SamuelNZ/VMRadar

**Comment by madlifer** [comment]
老哥,你的fork是不是人物位移问题得修修了.

**Comment by 1244453393** [comment]
This project is very good,But it takes up a very high GPU,This makes the game FPS very low

**Comment by Pochtidruid** [comment]
@Jerry1211 thx u for release, the best radar I've ever seen.
1 note - please add the grid (100m, 1km) on the map as on the original radar and map in the game

**Comment by Jerry1211** [comment]
@Pochtidruid  done

**Comment by Pochtidruid** [comment]
@Jerry1211 perfect, thx u!

**Comment by Pochtidruid** [comment]
@Jerry1211 btw how does the line of sight work in your fork? i mean in the original radar the line is displayed if the enemy looks at you, in your fork, the line is displayed after an enemy make shot, or its something wrong with me?

**Comment by jacxing** [comment]
@Jerry1211 hi am having a problem, after finishing compiling and everything the radar is running  but all i see is grey background and its taking 80% of my video card (GTX 1060) so it should be running.
what do you think the problem is ?

**Comment by liuguanxiong** [comment]
@Jerry1211 are you locate at Toronto as well?

**Comment by Jerry1211** [comment]
not anymore

**Comment by liuguanxiong** [comment]
@Jerry1211 what happened to vmradar.net? Are you guys closing it for update or permanently closed?
