### ISSUE TITLE
UnsatisfiedLinkError: Can't find dependent libraries

### ISSUE THREAD

**Issue by SunnyZo** [AiYinZiLeGong/PUBG-Radar#95]
Hey. Asking you for help. What can it be?

![image](https://user-images.githubusercontent.com/36954290/36840559-780098e6-1d56-11e8-9ac2-ecee5f177ec4.png)

**Comment by NatsumeZhang** [comment]
It works on Jdk1.8，I guess your VM verison is lower

**Comment by shunlibest** [comment]
I have the same problem. Do you resove it?
my VM is VMware® Workstation 14 Pro. I think it is latest .
