### ISSUE TITLE
RenderBadPicture(2)

### ISSUE THREAD

**Issue by Cron5** [AiYinZiLeGong/PUBG-Radar#98]
Hi there.
Im getting this error while running radar

> Error of failed request: RenderBadPicture

Ubuntu 17.10.1.
- PC with the game ip 192.168.1.35
- laptop Ubuntu ip 192.168.1.37
- Router ip 192.168.1.1

Im using the following parameters to run:

- sudo arpspoof -i enp8s0 -t 192.168.1.35 192.168.1.1
- sudo arpspoof -i enp8s0 -t 192.168.1.1 192.168.1.35
- sudo java -jar pubg-radar-with-dependencies.jar 192.168.1.37 PortFilter 192.168.1.35

When im running the radar a new window pops up, it let me choose network interface and near 192.168.1.37 i see "null"(im not sure what should i see there).
Any idea how to fix?

**Comment by N1teW0lf** [comment]
![](https://user-images.githubusercontent.com/12907074/36323537-8d788f58-1351-11e8-9826-6436c3cdc106.png)

**Comment by Cron5** [comment]
I read the Readme a few times. I do not fully understand what needs to be done there. 
- What does it mean to "switch branch linux"? 
- The last is also not entirely clear, <pc pubg ip?> <choose PortFiletr or PPTP> [whose ip is this?].

**Comment by Norxy** [comment]
Switch branch from master to linux on download page, up left

**Comment by NatsumeZhang** [comment]
@Cron5 
![image](https://user-images.githubusercontent.com/16576667/36934444-898fe556-1f24-11e8-8525-c28ba36bf417.png)
![image](https://user-images.githubusercontent.com/16576667/36934446-8d124c8c-1f24-11e8-8813-2d3ae45e3b10.png)
